Repository wepublish/wepublish, pull requests merged in 2020-11, with the labels that each got.

#67 Add delete token permission to AllPermissions
  packages/api/src/graphql/permissions.ts
Labels: PR: Bug Fix :bug:

#71 save preTitel in teaser
  packages/editor/src/client/blocks/types.ts
Labels: PR: Bug Fix :bug:

#79 Updated github-actions
  .github/workflows/main.yml
Labels: PR: Internal :house:

#80 Added code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: PR: Docs :memo:, PR: Internal :house:

#81 New readme page
  .vscode/launch.json
  .vscode/settings.json
  FAQ.md
  README.md
  packages/api-db-karma/.npmignore
  packages/api-db-karma/package.json
  packages/api-db-karma/src/index.ts
  packages/api-db-karma/src/model.ts
  packages/api-db-karma/src/tsconfig.json
  packages/api-db-karma/src/version.ts
  packages/api-db-memory/.npmignore
  packages/api-db-memory/index.d.ts
  packages/api-db-memory/index.js
  packages/api-db-memory/package.json
  packages/api-db-memory/src/index.ts
  packages/api-db-memory/src/tsconfig.json
  packages/api-db-memory/src/version.ts
Labels: PR: Docs :memo:, PR: Internal :house:

#63 f/WEP-90 navigations-menu
  packages/api-db-mongodb/src/db/navigation.ts
  packages/api/src/db/navigation.ts
  packages/api/src/graphql/mutation.ts
  packages/api/src/graphql/query.ts
  packages/editor/package.json
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/navigations.graphql
  packages/editor/src/client/app.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/navigationEditPanel.tsx
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/navigationList.tsx
Labels: PR: New Feature :heart:

#57 F/wep 78 editor multi language switch
  packages/editor/src/client/base.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Internal :house:, PR: New Feature :heart:

#82 Update faq.md
  FAQ.md
Labels: PR: Docs :memo:

#85 F/wep 90 navigation menu display
  examples/website/src/shared/navigation/navigationBar.tsx
  examples/website/src/shared/route/baseTemplateContainer.tsx
  examples/website/src/shared/types.ts
Labels: PR: Internal :house:
