Repository wepublish/wepublish, pull requests merged in 2020-12, with the labels that each got.

#89 F/wep 110 favicon
  packages/editor/src/server/index.tsx
  packages/editor/static/favicon-128.png
  packages/editor/static/favicon-64.png
  yarn.lock
Labels: PR: Polish :nail_care:

#91 B/wep 90 navigation menu display
  examples/website/src/shared/route/baseTemplateContainer.tsx
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/route/router.tsx
Labels: PR: Internal :house:

#92 F/wep 88 hide authors
  packages/api-db-mongodb/src/db/article.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/article.graphql
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/specs/article.ts
  packages/api/src/db/article.ts
  packages/api/src/graphql/article.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: New Feature :heart:

#94 Bug fix - Author list now updates the UI after an author is removed
  packages/editor/src/client/routes/authorList.tsx
Labels: PR: Bug Fix :bug:

#96 F/wep 131 richtext table for website client
  examples/website/src/shared/atoms/richText.tsx
Labels: PR: Breaking Change :boom:

#101 bug fix - Delete-Dialog not disappearing in pageList
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Bug Fix :bug:

#100 T/api article tests
  packages/api/__tests__/api/private/article.graphql
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/specs/__snapshots__/article.ts.snap
  packages/api/__tests__/specs/article.ts
Labels: PR: Internal :house:

#105 T/api author tests
  packages/api/__tests__/specs/__snapshots__/author.ts.snap
  packages/api/__tests__/specs/author.ts
Labels: PR: Internal :house:

#107 test(api): api page tests
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/page.graphql
  packages/api/__tests__/specs/__snapshots__/page.ts.snap
  packages/api/__tests__/specs/page.ts
Labels: PR: Internal :house:

#106 Align new navigation button to the right (#84)
  packages/editor/src/client/routes/navigationList.tsx
Labels: PR: Bug Fix :bug:

#102 F/wep 116 add peer call to action info
  .github/workflows/main.yml
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/types.ts
  packages/api-db-mongodb/src/db/peer.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/peer.ts
  packages/api/src/graphql/peer.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/peer.graphql
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
Labels: PR: New Feature :heart:

#108 add placeholder image and use it
  packages/editor/src/client/atoms/chooseEditImage.tsx
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/static/placeholder-240x240.png
Labels: PR: Bug Fix :bug:

#114 T/api page block
  packages/api/__tests__/specs/__snapshots__/page.ts.snap
  packages/api/__tests__/specs/page.ts
Labels: PR: Internal :house:

#93 F/wep 87 social media metatags
  .github/workflows/main.yml
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/types.ts
  packages/api-db-mongodb/src/db/article.ts
  packages/api-db-mongodb/src/db/page.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/article.graphql
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/specs/__snapshots__/article.ts.snap
  packages/api/__tests__/specs/article.ts
  packages/api/src/db/article.ts
  packages/api/src/db/page.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/page.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: New Feature :heart:

#112 F/wep 136 richtext toolbar style
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/atoms/toolbar.tsx
  packages/editor/src/client/blocks/richTextBlock/buttons.tsx
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/tableMenu.tsx
Labels: PR: Polish :nail_care:

#117 T/api user user role
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/user.graphql
  packages/api/__tests__/api/private/userRole.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/__tests__/specs/user.ts
  packages/api/__tests__/specs/userRole.ts
Labels: PR: Internal :house:

#116 Mail provider adapter
  examples/api/src/index.ts
  packages/api-db-mongodb/src/adapter.ts
  packages/api-db-mongodb/src/db/mailLog.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/db/adapter.ts
  packages/api/src/db/mailLog.ts
  packages/api/src/graphql/mailLog.ts
  packages/api/src/graphql/mutation.ts
  packages/api/src/index.ts
  packages/api/src/mails/MailchimpMailProvider.ts
  packages/api/src/mails/MailgunMailProvider.ts
  packages/api/src/mails/mailProvider.ts
  packages/api/src/server.ts
  packages/editor/src/client/api/index.ts
  yarn.lock
Labels: PR: New Feature :heart:
