Repository wepublish/wepublish, pull requests merged in 2020-10, with the labels that each got.

#52 Update apollo-client dependencies
  packages/editor/codegen.yml
  packages/editor/package.json
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/authContext.tsx
  packages/editor/src/client/index.tsx
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/routes/userRoleList.tsx
  yarn.lock
Labels: PR: Internal :house:

#55 Cleanup of old version number mechanism
  examples/api/package.json
  examples/api/src/version.ts
  packages/api-db-mongodb/package.json
  packages/api-db-mongodb/src/version.ts
  packages/api-media-karma/package.json
  packages/api-media-karma/src/version.ts
  packages/api/package.json
  packages/api/src/version.ts
  packages/editor/package.json
  packages/editor/src/shared/version.ts
  packages/oauth2/package.json
  packages/oauth2/src/server/version.ts
  scripts/syncPackageInfo.js
Labels: PR: Internal :house:

#56 bug fix - transform metadata properties to avoid errors on save
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Bug Fix :bug:

#58 Removed double dependency
  packages/api/package.json
  yarn.lock
Labels: PR: Internal :house:

#53 F/wep 78 editor multi language
  packages/editor/package.json
  packages/editor/src/client/base.tsx
  packages/editor/src/client/blocks/embedBlock.tsx
  packages/editor/src/client/blocks/imageBlock.tsx
  packages/editor/src/client/blocks/imageGalleryBlock.tsx
  packages/editor/src/client/blocks/linkPageBreakBlock.tsx
  packages/editor/src/client/blocks/listicleBlock.tsx
  packages/editor/src/client/blocks/quoteBlock.tsx
  packages/editor/src/client/blocks/richTextBlock.tsx
  packages/editor/src/client/blocks/teaserGridBlock.tsx
  packages/editor/src/client/blocks/titleBlock.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/index.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/login.tsx
  packages/editor/src/client/panel/articleChoosePanel.tsx
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/authorEditPanel.tsx
  packages/editor/src/client/panel/embedEditPanel.tsx
  packages/editor/src/client/panel/galleryListEditPanel.tsx
  packages/editor/src/client/panel/imageEditPanel.tsx
  packages/editor/src/client/panel/imageSelectPanel.tsx
  packages/editor/src/client/panel/imageUploadPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
  packages/editor/src/client/panel/resetUserPasswordPanel.tsx
  packages/editor/src/client/panel/teaserEditPanel.tsx
  packages/editor/src/client/panel/teaserSelectAndEditPanel.tsx
  packages/editor/src/client/panel/teaserSelectPanel.tsx
  packages/editor/src/client/panel/tokenGeneratePanel.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/panel/userRoleEditPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/authorList.tsx
  packages/editor/src/client/routes/imageList.tsx
  packages/editor/src/client/routes/pageEditor.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/routes/peerList.tsx
  packages/editor/src/client/routes/tokenList.tsx
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/routes/userRoleList.tsx
  packages/editor/src/server/index.tsx
  tsconfig.base.json
  yarn.lock
Labels: PR: Internal :house:, PR: New Feature :heart:
