Repository wepublish/wepublish, pull requests merged in 2021-10, with the labels that each got.

#372 peering between different versions
  packages/api/src/error.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/peer.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/routes/peerList.tsx
Labels: PR: Bug Fix :bug:, PR: Polish :nail_care:

#376 F/wpc 522 add font color to peered articles
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/types.ts
  packages/api-db-mongodb/src/db/peer.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/peer.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/api/public/peer.graphql
  packages/api/__tests__/fakePeerAdminSchema.json
  packages/api/__tests__/specs/__snapshots__/peer.ts.snap
  packages/api/__tests__/specs/peer.ts
  packages/api/src/db/peer.ts
  packages/api/src/graphql/peer.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/peer.graphql
  packages/editor/src/client/atoms/iconButtonTooltip.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
Labels: PR: Polish :nail_care:

#377 make state colors of articles/pages consistent
  packages/editor/src/client/global.less
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageEditor.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Internal :house:

#379 chore(api): prettier cleanup
  package.json
  packages/api/src/server.ts
Labels: PR: Internal :house:
