Repository wepublish/wepublish, pull requests merged in 2021-08, with the labels that each got.

#330 wpc-453-make-articles-highlighted
  packages/editor/src/client/base.tsx
Labels: PR: Polish :nail_care:

#329 wpc-460 add frame around description in member plan panel
  packages/editor/src/client/global.less
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
Labels: PR: Polish :nail_care:

#326 wpc-461-add-frame-around-author-bio-info
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/panel/authorEditPanel.tsx
Labels: PR: Polish :nail_care:

#309 wpc-211-comment-length-validation
  examples/website/src/shared/molecules/commentTemplate.tsx
  packages/api/src/error.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/utility.ts
Labels: PR: Internal :house:

#310 Add image cta in peer profile
  packages/api-db-mongodb/src/db/peer.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/peer.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/specs/__snapshots__/peer.ts.snap
  packages/api/src/db/peer.ts
  packages/api/src/graphql/peer.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/peer.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
Labels: PR: New Feature :heart:

#333 wpc-459-add-image-description
  packages/editor/src/client/global.less
  packages/editor/src/client/routes/imageList.tsx
Labels: PR: Polish :nail_care:

#339 wpc-444-reply to comments only when logged in
  examples/website/src/shared/molecules/commentTemplate.tsx
Labels: PR: Polish :nail_care:
