Repository wepublish/wepublish, pull requests merged in 2021-03, with the labels that each got.

#200 Remove unmaintained translation files
  packages/editor/src/client/base.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Internal :house:

#199 Added SEO guide link
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
Labels: PR: Polish :nail_care:

#201 wpc-180-fix broken route for breaking articles
  examples/website/src/shared/blocks/blockRenderer.tsx
Labels: PR: Bug Fix :bug:

#153 F/WPC-87 & F/WPC-55 comment frontend functionality
  examples/website/package.json
  examples/website/src/shared/atoms/primaryButton.tsx
  examples/website/src/shared/atoms/richText.tsx
  examples/website/src/shared/blocks/blockRenderer.tsx
  examples/website/src/shared/blocks/listicalBlock.tsx
  examples/website/src/shared/blocks/peerPageBreak.tsx
  examples/website/src/shared/blocks/richTextBlock.stories.tsx
  examples/website/src/shared/blocks/richTextBlock.tsx
  examples/website/src/shared/blocks/richTextBlock/editor/elements.ts
  examples/website/src/shared/blocks/richTextBlock/editor/formats.ts
  examples/website/src/shared/blocks/richTextBlock/editor/normalizing.ts
  examples/website/src/shared/blocks/richTextBlock/editor/plugins.tsx
  examples/website/src/shared/blocks/richTextBlock/editor/render.tsx
  examples/website/src/shared/blocks/richTextBlock/editor/wepublishEditor.ts
  examples/website/src/shared/blocks/richTextBlock/richTextBlock.tsx
  examples/website/src/shared/molecules/commentTemplate.tsx
  examples/website/src/shared/navigation/articleFooter.tsx
  examples/website/src/shared/query.tsx
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/authorTemplateContainer.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/footerContainer.tsx
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/types.ts
  examples/website/static/icons/avatar.jpg
  yarn.lock
Labels: PR: New Feature :heart:

#195 Wpc 205 character counter
  packages/editor/src/client/blocks/listicleBlock.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: Internal :house:

#205 Add hotkey shortcuts to Richtext Editor
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
Labels: PR: Polish :nail_care:

#206 B/wpc 245 image selection disabled in edit peer
  packages/editor/src/client/atoms/chooseEditImage.tsx
Labels: PR: Bug Fix :bug:, bug

#207 Article Preview Links
  examples/api/src/index.ts
  examples/website/src/shared/route/articleTemplateContainer.tsx
  packages/api-db-mongodb/src/db/article.ts
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/__tests__/utility.ts
  packages/api/src/context.ts
  packages/api/src/db/article.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/urlAdapter.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articlePreviewLinkPanel.tsx
  packages/editor/src/client/routes/articleList.tsx
Labels: PR: New Feature :heart:

#211 hotkey cmd support for macs
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
Labels: PR: Polish :nail_care:

#212 fixed links in example website
  examples/website/src/shared/blocks/richTextBlock/editor/render.tsx
Labels: bug

#194 F/wpc 88 update comment
  examples/website/src/shared/molecules/commentTemplate.tsx
  examples/website/src/shared/query.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/types.ts
Labels: PR: New Feature :heart:

#209 F/wpc 244 infer link protocol
  packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
Labels: PR: Polish :nail_care:

#210 b/Wpc-229-make-duplicated-articles-appear-immediatly
  packages/editor/src/client/app.tsx
  packages/editor/src/client/global.less
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Internal :house:

#213 b/WPC-261-embed-close-button-labeled-as-confirm
  packages/editor/src/client/panel/embedEditPanel.tsx
Labels: PR: Bug Fix :bug:

#214 f/wpc-256-see-the-max-amount-of-characters
  packages/editor/src/client/panel/articleMetadataPanel.tsx
Labels: PR: Internal :house:

#216 f/WPC-276-highlight-article-after-being-unpublished
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Polish :nail_care:

#219 Disable save without peer data and handle errors of invalid tokens
  packages/api/src/graphql/peer.ts
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/peerEditPanel.tsx
Labels: PR: Bug Fix :bug:

#218 Added color to the table in the example website
  examples/website/src/shared/blocks/richTextBlock/editor/render.tsx
Labels: PR: Internal :house:

#217 Selected authors stay selected during search
  packages/editor/src/client/panel/articleMetadataPanel.tsx
Labels: PR: Bug Fix :bug:

#225 f/wpc-296-add-slug-guide
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
Labels: PR: Polish :nail_care:

#227 f/wpc-266-add-getCommentUrl-in-UrlAdapter-interface
  examples/api/src/index.ts
  packages/api/__tests__/utility.ts
  packages/api/src/urlAdapter.ts
Labels: PR: Breaking Change :boom:

#222 Add missing translations to userlist panel
  packages/editor/src/client/locales/en.json
Labels: PR: Bug Fix :bug:

#223 fix table column width
  packages/editor/src/client/routes/articleList.tsx
Labels: PR: Bug Fix :bug:

#224 f/wpc-255-character-counter-count-more-blocks
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: Internal :house:

#228 use Visibility API to check if still logged in
  packages/api/src/graphql/query.private.ts
  packages/editor/package.json
  packages/editor/src/client/authContext.tsx
  packages/editor/src/client/index.tsx
  yarn.lock
Labels: PR: New Feature :heart:
