Repository wepublish/wepublish, pull requests merged in 2021-05, with the labels that each got.

#256 Color all rows on comment table
  packages/editor/src/client/global.less
Labels: PR: Polish :nail_care:

#258 Add polis embed block
  examples/website/src/shared/atoms/polisEmbed.tsx
  examples/website/src/shared/blocks/blockRenderer.tsx
  examples/website/src/shared/blocks/embedBlock.tsx
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/types.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/src/db/block.ts
  packages/api/src/graphql/blocks.ts
  packages/editor/src/client/api/block.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/blocks/embedBlock.tsx
  packages/editor/src/client/blocks/embeds/polis.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/embedEditPanel.tsx
Labels: PR: New Feature :heart:

#261 F/wpc 274 redirect back on comment after login
  examples/website/src/shared/molecules/commentTemplate.tsx
Labels: PR: New Feature :heart:

#264 b/wpc-369-make-default-publishing-time-5
  packages/editor/src/client/atoms/dateTimePicker.tsx
Labels: PR: Bug Fix :bug:

#257 placement of date picker in user subscription panel
  packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
Labels: PR: Bug Fix :bug:

#251 show parent comment in comment review panel
  packages/api/src/graphql/comment.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/src/client/api/comment.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/commentList.tsx
Labels: PR: Polish :nail_care:

#270 Show publish date in article and page list
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Polish :nail_care:

#263 f/wpc-341-order-comments-by-state
  .github/workflows/main.yml
  packages/api-db-mongodb/src/db/comment.ts
  packages/editor/src/client/routes/commentList.tsx
Labels: PR: Internal :house:
