Repository wepublish/wepublish, pull requests merged in 2021-06, with the labels that each got.

#274 F/wpc 353 show pending publish date
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Polish :nail_care:

#272 validation for url peering to host
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/routes/peerList.tsx
Labels: PR: Internal :house:

#277 fix(website): removed comments from graphql query for peer articles
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/gqlFragments.ts
Labels: PR: Internal :house:

#278 F/wpc 22 update
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/routes/peerList.tsx
Labels: PR: Bug Fix :bug:

#279 wpc-397 metadata close button
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Polish :nail_care:

#281 Bug fix for peered article that contain a teaser grid block
  packages/api/src/graphql/article.ts
  packages/api/src/utility.ts
Labels: PR: Bug Fix :bug:

#284 token save notification
  packages/editor/__tests__/specs/__snapshots__/tokenGeneratePanel.tsx.snap
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/tokenGeneratePanel.tsx
Labels: PR: Polish :nail_care:

#287 reverse enums also for PeerArticleTeasers and PageTeasers
  packages/api/src/utility.ts
Labels: PR: Bug Fix :bug:

#288 Allow previews for peered articles
  examples/api/src/index.ts
  examples/website/src/shared/route/routeContext.ts
  packages/api/__tests__/utility.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/urlAdapter.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/teaserSelectPanel.tsx
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#286 F/wpc 408 navbar collapse
  packages/editor/src/client/base.tsx
  packages/editor/src/client/global.less
Labels: PR: Polish :nail_care:

#285 wpc-421 adding graphql description for public queries and mutations
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/query.public.ts
Labels: PR: Internal :house:

#283 F/wpc 165 article status indicator
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/global.less
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Polish :nail_care:
