Repository wepublish/wepublish, pull requests merged in 2021-07, with the labels that each got.

#291 b/wpc-423-ui-fixes
  packages/editor/src/client/atoms/editorTemplate.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/global.less
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Polish :nail_care:

#293 remove unused deps
  packages/api/package.json
  packages/editor/package.json
  packages/editor/src/client/api/index.ts
  packages/oauth2/package.json
  yarn.lock
Labels: PR: Internal :house:

#294 Add properties tab to metadata
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
Labels: PR: Polish :nail_care:

#295 Handle URLs inside a peer article
  .github/workflows/main.yml
  examples/website/src/shared/blocks/blockRenderer.tsx
  examples/website/src/shared/route/authorTemplateContainer.tsx
  examples/website/src/shared/route/tagTemplateContainer.tsx
  examples/website/src/shared/teasers/breakingTeaser.tsx
  examples/website/src/shared/teasers/defaultTeaser.tsx
  examples/website/src/shared/teasers/imageTeaser.tsx
  examples/website/src/shared/teasers/textTeaser.tsx
Labels: PR: Bug Fix :bug:

#296 Use JS SDK instead of iframe
  examples/website/src/shared/atoms/polisEmbed.tsx
  packages/editor/src/client/blocks/embeds/polis.tsx
Labels: PR: Internal :house:, PR: Polish :nail_care:

#297 Feature deployment
  .github/workflows/deploy.yml
  .github/workflows/pr_close.yml
  config/create-gke-manifest.js
  config/notify.js
  config/package.json
  config/yarn.lock
  docker-compose.yml
  package.json
  packages/oauth2/package.json
Labels: enhancement

#301 add default peering
  config/create-gke-manifest.js
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/server/index.tsx
  packages/editor/src/shared/types.ts
Labels: PR: New Feature :heart:

#305 Preview links for pages
  examples/api/src/index.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/__tests__/utility.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/urlAdapter.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/pagePreviewLinkPanel.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: New Feature :heart:

#302 wpc-435-fix image dropdown menu
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/atoms/chooseEditImage.tsx
Labels: PR: Bug Fix :bug:

#308 Page slug can be empty string
  packages/api/src/graphql/query.public.ts
Labels: bug

#312 Updated translations from Phrase
  packages/editor/src/client/base.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Polish :nail_care:

#317 Only deploy if PR from same repo
  .github/workflows/deploy.yml
Labels: internal

#313 Update react to v17
  dockerfile
  examples/website/package.json
  packages/editor/__tests__/setup.ts
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userRoleEditPanel.tsx.snap
  packages/editor/package.json
  packages/editor/src/client/app.tsx
  packages/editor/src/client/atoms/blockList.tsx
  packages/editor/src/client/atoms/helpers.ts
  packages/editor/src/client/atoms/listInput.tsx
  packages/editor/src/client/atoms/overlay.tsx
  packages/editor/src/client/atoms/toolbar.tsx
  packages/editor/src/client/atoms/typographicTextArea.tsx
  packages/editor/src/client/atoms/typography.tsx
  packages/editor/src/client/blocks/linkPageBreakBlock.tsx
  packages/editor/src/client/blocks/listicleBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/teaserGridBlock.tsx
  packages/editor/src/client/index.tsx
  packages/editor/src/client/login.tsx
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/authorList.tsx
  packages/editor/src/client/routes/imageList.tsx
  packages/editor/src/client/routes/memberPlanList.tsx
  packages/editor/src/client/routes/navigationList.tsx
  packages/editor/src/client/routes/pageEditor.tsx
  packages/editor/src/client/routes/paymentMethodList.tsx
  packages/editor/src/client/routes/peerList.tsx
  packages/editor/src/client/routes/tokenList.tsx
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/routes/userRoleList.tsx
  packages/editor/webpack.config.ts
  yarn.lock
Labels: PR: Internal :house:

#307 added canonicalUrl field for article
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/types.ts
  packages/api-db-mongodb/src/db/article.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/src/db/article.ts
  packages/api/src/graphql/article.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: New Feature :heart:

#322 WPC-454 Change pages icon
  packages/editor/src/client/base.tsx
Labels: PR: Polish :nail_care:

#324 wpc-456-payment-methods-icon
  packages/editor/src/client/base.tsx
Labels: PR: Polish :nail_care:

#323 wpc-455-image-library-icon
  packages/editor/src/client/base.tsx
Labels: PR: Polish :nail_care:

#325 wpc-457-reset-password-icon
  packages/editor/src/client/routes/userList.tsx
Labels: PR: Polish :nail_care:

#327 Translations update from Weblate
  packages/editor/src/client/locales/fr.json
Labels: PR: Polish :nail_care:

#268 F/wpc 331 docs
  .gitignore
  docs/.nojekyll
  docs/README.md
  docs/assets/logo.png
  docs/commenting.md
  docs/emailtemplates.md
  docs/index.html
Labels: PR: Docs :memo:

#290 Use email-templates and pug to render mail templates
  docs/emailtemplates.md
  examples/api/src/index.ts
  examples/api/templates/emails/base.pug
  examples/api/templates/emails/loginLink/html.pug
  examples/api/templates/emails/loginLink/subject.pug
  examples/api/templates/emails/memberSubscriptionPayment/offSessionPaymentOneWeekBefore/html.pug
  examples/api/templates/emails/memberSubscriptionPayment/offSessionPaymentOneWeekBefore/subject.pug
  examples/api/templates/emails/memberSubscriptionPayment/onSessionAfter/html.pug
  examples/api/templates/emails/memberSubscriptionPayment/onSessionAfter/subject.pug
  examples/api/templates/emails/memberSubscriptionPayment/onSessionBefore/html.pug
  examples/api/templates/emails/memberSubscriptionPayment/onSessionBefore/subject.pug
  examples/api/templates/emails/newMemberSubscription/html.pug
  examples/api/templates/emails/newMemberSubscription/subject.pug
  examples/api/templates/emails/passwordReset/html.pug
  examples/api/templates/emails/passwordReset/subject.pug
  examples/api/templates/emails/renewedMemberSubscription/html.pug
  examples/api/templates/emails/renewedMemberSubscription/subject.pug
  examples/api/templates/emails/testMail/html.pug
  examples/api/templates/emails/testMail/subject.pug
  packages/api/__tests__/specs/mailchimpMailProvider.ts
  packages/api/__tests__/utility.ts
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/index.ts
  packages/api/src/jobs.ts
  packages/api/src/mails/MailchimpMailProvider.ts
  packages/api/src/mails/MailgunMailProvider.ts
  packages/api/src/mails/mailContext.ts
  packages/api/src/mails/mailProvider.ts
  packages/api/src/memberContext.ts
  packages/editor/src/client/atoms/chooseEditImage.tsx
  packages/editor/src/client/locales/fr.json
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:
