Repository wepublish/wepublish, pull requests merged in 2021-01, with the labels that each got.

#118 F/wep 159 refactor seperate editor tools modules
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/atoms/toolbar.tsx
  packages/editor/src/client/blocks/richTextBlock/buttons.tsx
  packages/editor/src/client/blocks/richTextBlock/editor.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/formats.ts
  packages/editor/src/client/blocks/richTextBlock/editor/plugins.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/render.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/utils.ts
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/buttons.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/linkButton.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/tableMenu.less
  packages/editor/src/client/blocks/richTextBlock/toolbar/tableMenu.tsx
Labels: PR: Internal :house:, refactoring

#120 Mail provider for Slack
  examples/api/package.json
  examples/api/src/SlackMailProvider.ts
  examples/api/src/index.ts
  examples/api/src/tsconfig.json
  yarn.lock
Labels: PR: Internal :house:

#121 API with hooks
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/events.ts
  packages/api/src/server.ts
  packages/api/src/utility.ts
  yarn.lock
Labels: PR: Internal :house:, PR: New Feature :heart:

#123 WEP-100 Reader Authentication
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/schema.ts
  packages/api/src/graphql/session.ts
  packages/api/src/graphql/user.ts
  packages/api/src/index.ts
  packages/editor/src/client/api/auth.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/login.tsx
Labels: PR: New Feature :heart:

#124 Mailgun improvements
  config/create-gke-manifest.js
  examples/api/src/index.ts
  packages/api/src/mails/MailgunMailProvider.ts
Labels: PR: Polish :nail_care:

#126 T/api peer
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/peer.graphql
  packages/api/__tests__/fakePeerAdminSchema.json
  packages/api/__tests__/setup.ts
  packages/api/__tests__/specs/__snapshots__/peer.ts.snap
  packages/api/__tests__/specs/peer.ts
  packages/api/package.json
  packages/api/src/context.ts
  yarn.lock
Labels: PR: Internal :house:

#129 Removed unused types
  examples/website/package.json
  yarn.lock
Labels: PR: Internal :house:

#130 T/api navigations
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/navigation.graphql
  packages/api/__tests__/specs/__snapshots__/navigation.ts.snap
  packages/api/__tests__/specs/navigation.ts
Labels: PR: Internal :house:

#125 Magic Login Links
  .github/workflows/main.yml
  .github/workflows/test.yml
  config/create-gke-manifest.js
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/user.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/api/public/user.graphql
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/__tests__/specs/session.ts
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/editor/src/client/api/auth.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/login.tsx
  packages/editor/src/client/route.tsx
Labels: PR: New Feature :heart:

#133 B/WEP-176-missing-userRole-translations
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Bug Fix :bug:

#132 B/WEP-173-fix-create-navigation-description
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/src/graphql/permissions.ts
Labels: PR: Bug Fix :bug:

#136 B/wep 174 fix focus empty rtb firefox
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/blocks/richTextBlock/editor/plugins.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/render.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/utils.ts
  packages/editor/src/client/blocks/richTextBlock/editor/wepublishEditor.ts
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/buttons.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/linkButton.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/tableMenu.tsx
Labels: PR: Bug Fix :bug:

#119 F/wep 121 re implement via normalizenode
  packages/editor/__tests__/specs/elements.test.ts
  packages/editor/__tests__/specs/normalizing.test.ts
  packages/editor/__tests__/utils.ts
  packages/editor/src/client/blocks/richTextBlock/editor/elements.ts
  packages/editor/src/client/blocks/richTextBlock/editor/normalizing.ts
  packages/editor/src/client/blocks/richTextBlock/editor/plugins.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/render.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/wepublishEditor.ts
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/tableMenu.tsx
Labels: PR: Internal :house:

#122 F/wep 152 commenting initial types schemas
  .github/workflows/main.yml
  examples/api/src/index.ts
  packages/api-db-mongodb/src/adapter.ts
  packages/api-db-mongodb/src/db/comment.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/comment.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/__tests__/specs/comment.ts
  packages/api/src/db/adapter.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/comment.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/query.ts
  packages/api/src/index.ts
  packages/editor/src/client/api/index.ts
Labels: PR: New Feature :heart:

#138 Cronjobs for nightly subscription payments
  examples/api/package.json
  examples/api/src/index.ts
  packages/api-db-mongodb/src/db/invoice.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/db/utility.ts
  packages/api/src/db/common.ts
  packages/api/src/db/invoice.ts
  packages/api/src/db/paymentMethod.ts
  packages/api/src/db/user.ts
  packages/api/src/events.ts
  packages/api/src/graphql/common.ts
  packages/api/src/graphql/invoice.ts
  packages/api/src/graphql/paymentMethod.ts
  packages/api/src/graphql/user.ts
  packages/api/src/index.ts
  packages/api/src/jobs.ts
  packages/api/src/payments/stripePaymentProvider.ts
  packages/api/src/server.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/panel/paymentMethodEditPanel.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
  yarn.lock
Labels: PR: New Feature :heart:

#140 Log all the things
  .github/workflows/main.yml
  config/create-gke-manifest.js
  examples/api/package.json
  examples/api/src/index.ts
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/jobs.ts
  packages/api/src/mails/mailProvider.ts
  packages/api/src/payments/paymentProvider.ts
  packages/api/src/payments/payrexxPaymentProvider.ts
  packages/api/src/payments/stripeCheckoutPaymentProvider.ts
  packages/api/src/payments/stripePaymentProvider.ts
  packages/api/src/server.ts
  yarn.lock
Labels: PR: Internal :house:, PR: New Feature :heart:

#115 F/wep 128 richtext table border colorpicker
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/__tests__/specs/elements.test.ts
  packages/editor/__tests__/specs/normalizing.test.ts
  packages/editor/package.json
  packages/editor/src/client/atoms/colorPicker.tsx
  packages/editor/src/client/atoms/emojiPicker.tsx
  packages/editor/src/client/atoms/toolbar.less
  packages/editor/src/client/atoms/toolbar.tsx
  packages/editor/src/client/blocks/richTextBlock/editor/elements.ts
  packages/editor/src/client/blocks/richTextBlock/editor/normalizing.ts
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/tableMenu.less
  packages/editor/src/client/blocks/richTextBlock/toolbar/tableMenu.tsx
  packages/editor/src/client/locales/en.json
Labels: PR: New Feature :heart:

#149 Edit user and subscription through public
  packages/api-db-mongodb/src/db/invoice.ts
  packages/api/src/context.ts
  packages/api/src/db/invoice.ts
  packages/api/src/error.ts
  packages/api/src/graphql/invoice.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/graphql/user.ts
Labels: PR: New Feature :heart:

#143 Pagination for tables and API
  packages/api-db-mongodb/src/db/user.ts
  packages/api/src/db/common.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/query.ts
  packages/api/src/graphql/user.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: New Feature :heart:

#134 B/WEP-175-fix-imageBlock
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/atoms/chooseEditImage.tsx
  packages/editor/src/client/atoms/focalPointInput.tsx
  packages/editor/src/client/atoms/listInput.tsx
  packages/editor/src/client/blocks/imageBlock.tsx
  packages/editor/src/client/blocks/imageGalleryBlock.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/authorEditPanel.tsx
  packages/editor/src/client/panel/galleryListEditPanel.tsx
  packages/editor/src/client/panel/imageSelectPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
  packages/editor/src/client/routes/imageList.tsx
Labels: PR: Bug Fix :bug:

#148 Create MemberPlan
  examples/api/src/index.ts
  packages/api-db-mongodb/src/db/invoice.ts
  packages/api-db-mongodb/src/db/memberPlan.ts
  packages/api-db-mongodb/src/db/paymentMethod.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/specs/user.ts
  packages/api/__tests__/utility.ts
  packages/api/src/context.ts
  packages/api/src/db/invoice.ts
  packages/api/src/db/memberPlan.ts
  packages/api/src/db/paymentMethod.ts
  packages/api/src/db/user.ts
  packages/api/src/error.ts
  packages/api/src/events.ts
  packages/api/src/graphql/invoice.ts
  packages/api/src/graphql/memberPlan.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/payment.ts
  packages/api/src/graphql/paymentMethod.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/graphql/schema.ts
  packages/api/src/graphql/user.ts
  packages/api/src/index.ts
  packages/api/src/jobs.ts
  packages/api/src/memberContext.ts
  packages/api/src/utility.ts
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/__tests__/specs/userEditPanel.tsx
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/memberPlan.graphql
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
  packages/editor/src/client/panel/paymentMethodEditPanel.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#151 config: explicit-module-boundary-types=off
  package.json
Labels: PR: Internal :house:

#147 F/wep 155 action on comment mutation
  packages/api-db-mongodb/src/db/comment.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/src/db/comment.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/permissions.ts
  packages/editor/src/client/api/index.ts
Labels: PR: New Feature :heart:

#137 b/WEP-178 chech ImageTeaserBlock if the image prop exist and has value, or set placeholder image instead
  examples/website/src/shared/teasers/imageTeaser.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/teaserEditPanel.tsx
Labels: PR: Bug Fix :bug:

#142 F/wep 195 update comment mutation
  packages/api-db-mongodb/src/db/comment.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/comment.ts
  packages/api/src/graphql/mutation.public.ts
Labels: PR: New Feature :heart:

#156 B/wep 201 query resolver functions
  packages/api/src/graphql/comment.ts
  packages/editor/src/client/api/index.ts
Labels: PR: Bug Fix :bug:

#155 Fixes for the next release
  examples/api/src/index.ts
  packages/api/src/error.ts
  packages/api/src/graphql/mutation.public.ts
Labels: PR: New Feature :heart:

#159 Bug Fix: replace cross-fetch with node-fetch
  packages/api/src/payments/payrexxPaymentProvider.ts
Labels: PR: Bug Fix :bug:
