Repository wepublish/wepublish, pull requests merged in 2021-02, with the labels that each got.

#161 fixed pagination and sort
  packages/api-db-mongodb/src/db/comment.ts
  packages/api/src/graphql/comment.ts
  packages/api/src/graphql/query.private.ts
Labels: PR: Bug Fix :bug:

#162 F/wpc 207 get public comment replies
  packages/api-db-mongodb/src/db/comment.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/comment.ts
Labels: PR: New Feature :heart:

#164 F/wpc 148 get public unapproved comments for auth user
  packages/api-db-mongodb/src/db/comment.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/comment.ts
  packages/editor/src/client/api/index.ts
Labels: PR: New Feature :heart:

#139 MailProvider Tests
  packages/api/__tests__/specs/mailchimpMailProvider.ts
  packages/api/__tests__/specs/mailgunMailProvider.ts
  packages/api/src/mails/MailchimpMailProvider.ts
Labels: PR: Internal :house:

#168 WPC-212 Rich Text in display only mode
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
Labels: PR: New Feature :heart:

#172 Pagination for article and page lists
  packages/api-db-mongodb/src/db/article.ts
  packages/api-db-mongodb/src/db/page.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: New Feature :heart:

#171 fix updateUser and updateSubscription mutations
  packages/api/src/graphql/mutation.public.ts
Labels: bug

#174 Fixing delete image bug
  packages/editor/src/client/routes/imageList.tsx
Labels: PR: Bug Fix :bug:

#173 Magic module error documentation
  FAQ.md
Labels: PR: Docs :memo:

#170 Author improvements
  packages/api-db-mongodb/src/db/author.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api/src/db/author.ts
  packages/api/src/graphql/author.ts
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/api/author.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/authorEditPanel.tsx
Labels: PR: New Feature :heart:

#175 add displayOnly prop to richText
  packages/editor/src/client/panel/peerEditPanel.tsx
Labels: PR: Bug Fix :bug:

#154 F/WPC-153 comments listing route
  .github/workflows/main.yml
  packages/editor/src/client/api/comment.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/app.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/commentList.tsx
Labels: PR: New Feature :heart:

#167 WPC-202 rich-text Get characters count method, and get string text method
  packages/editor/src/client/blocks/richTextBlock/editor/wepublishEditor.ts
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: New Feature :heart:

#157 Comments
  .github/workflows/main.yml
  examples/api/src/index.ts
  packages/api-db-mongodb/src/adapter.ts
  packages/api-db-mongodb/src/db/comment.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/comment.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/__tests__/specs/comment.ts
  packages/api/src/db/adapter.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/comment.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/index.ts
  packages/editor/src/client/api/comment.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/app.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/commentList.tsx
Labels: PR: New Feature :heart:

#178 F/WPC-199 improve metadata clarity
  FAQ.md
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
Labels: PR: Polish :nail_care:

#181 Unique page slug
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/specs/__snapshots__/page.ts.snap
  packages/api/__tests__/specs/page.ts
  packages/api/src/error.ts
  packages/api/src/graphql/mutation.private.ts
Labels: PR: New Feature :heart:

#183 fixed editor focus
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
Labels: bug

#179 f/WPC-3-editeable-slug-field
  FAQ.md
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: Internal :house:

#185 Wpc 20 duplicate articles and pages
  packages/api/src/graphql/mutation.private.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: New Feature :heart:

#180 f/WPC-200-sync-title-lead-with-metadata
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: Internal :house:

#184 add ability to display only one line
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/routes/commentList.tsx
Labels: PR: New Feature :heart:

#188 check first if visitor is authenticated or not
  packages/api/src/graphql/article.ts
Labels: PR: Bug Fix :bug:

#192 Added a new seoTitle field to the article metadata
  packages/api-db-mongodb/src/db/article.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api/src/db/article.ts
  packages/api/src/graphql/article.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
Labels: PR: Internal :house:

#186 f/wpc-56 & wpc-91 richtext editor link button and URL validation
  .github/workflows/main.yml
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/linkButton.tsx
  packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: New Feature :heart:

#196 B/wpc 224 logout
  packages/editor/src/client/index.tsx
  packages/editor/src/client/route.tsx
Labels: PR: Bug Fix :bug:

#197 f/WPC-228-more-clear-slug-field
  packages/api/src/graphql/mutation.private.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Polish :nail_care:

#198 Enhanced User address
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/user.ts
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:
