Repository wepublish/wepublish, pull requests merged in 2021-11, with the labels that each got.

#397 initialize calendar with last publication date
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
Labels: PR: Polish :nail_care:

#396 F/wpc 567 pending notification for future publications
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Polish :nail_care:

#398 new block for bildwurf ads
  examples/website/src/shared/atoms/bildwurfAdEmbed.tsx
  examples/website/src/shared/blocks/embedBlock.tsx
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/types.ts
  packages/api/src/db/block.ts
  packages/api/src/graphql/blocks.ts
  packages/editor/src/client/api/block.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/blocks/embedBlock.tsx
  packages/editor/src/client/blocks/embeds/bildwurfAd.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/panel/embedEditPanel.tsx
Labels: PR: New Feature :heart:

#83 Use E2E Tests for proper integration testing
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .gitignore
  config/create-gke-manifest.js
  config/utilities.js
  package.json
  packages/api/src/server.ts
  packages/editor/src/client/app.tsx
  packages/editor/src/client/authContext.tsx
  packages/editor/src/client/index.tsx
  packages/editor/src/client/login.tsx
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
  packages/editor/src/server/index.tsx
  tests/e2e.ts
  yarn.lock
Labels: PR: Polish :nail_care:, PR: Internal :house:

#402 changed paymentProviderCustomer to an array
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/user.ts
  packages/api/src/memberContext.ts
  packages/api/src/payments/paymentProvider.ts
Labels: PR: New Feature :heart:, PR: Internal :house:

#408 updated apollo-server-express to 2.25.3
  packages/api-db-mongodb/src/tsconfig.json
  packages/api/package.json
  packages/api/src/server.ts
  packages/api/src/tsconfig.json
  yarn.lock
Labels: PR: Internal :house:

#404 date fixes on calendar picker
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
Labels: PR: Bug Fix :bug:

#410 small bug fix for example website
  examples/website/src/shared/route/articleTemplateContainer.tsx
Labels: bug

#419 updated yarn lock
  yarn.lock
Labels: internal

#420 updated auto generated file
  packages/editor/src/client/api/index.ts
Labels: internal

#401 BAJ-5_upload_size
  config/create-gke-manifest.js
  packages/editor/package.json
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/imageEditPanel.tsx
  packages/editor/src/client/panel/imageSelectPanel.tsx
  packages/editor/src/client/panel/imageUploadPanel.tsx
  packages/editor/src/client/utility.ts
  packages/editor/src/server/index.tsx
  packages/editor/src/shared/types.ts
  yarn.lock
Labels: PR: New Feature :heart:

#306 Public mutation to cancel membership
  packages/api/src/error.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/memberContext.ts
Labels: PR: New Feature :heart:

#422 F/wpc 574 img library translation
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/imageEditPanel.tsx
Labels: PR: Polish :nail_care:

#425 e2e tests
  .github/workflows/deploy.yml
Labels: internal

#423 Update of stripePaymentProvider
  packages/api/src/payments/stripePaymentProvider.ts
Labels: PR: Internal :house:

#417 F/wpc 578 highlight missing field article metadata
  packages/editor/src/client/atoms/descriptionListwithMessage.tsx
  packages/editor/src/client/atoms/infoMessage.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/publishArticlePanel.tsx
  tests/e2e.ts
Labels: PR: Polish :nail_care:

#426 F/wpc 568 fix upload image error
  packages/editor/src/client/atoms/draggable.tsx
Labels: PR: Bug Fix :bug:

#418 f/wpc-579 missing fields highlighted in orange in page publish panel
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
Labels: PR: Polish :nail_care:

#428 bug fix for updating user subscription
  packages/api/src/graphql/mutation.public.ts
Labels: PR: Bug Fix :bug:

#432 Send Login Links from the Editor
  examples/api/src/index.ts
  packages/api/__tests__/utility.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/urlAdapter.ts
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/userEditPanel.tsx
Labels: PR: New Feature :heart:

#429 manual checkIntentStatus for Stripe and Payrexx
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/payments/paymentProvider.ts
  packages/api/src/payments/payrexxPaymentProvider.ts
  packages/api/src/payments/stripeCheckoutPaymentProvider.ts
  packages/api/src/payments/stripePaymentProvider.ts
  yarn.lock
Labels: PR: New Feature :heart:
