Repository wepublish/wepublish, pull requests merged in 2021-09, with the labels that each got.

#338 wpc-462-add-link-input
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/__tests__/specs/authorEditPanel.tsx
  packages/editor/src/client/panel/authorEditPanel.tsx
Labels: PR: Polish :nail_care:

#345 move authors position in the navigation
  packages/editor/src/client/base.tsx
Labels: PR: Polish :nail_care:

#340 Show comment characters length
  examples/website/src/shared/molecules/commentTemplate.tsx
  examples/website/src/shared/utility.ts
Labels: PR: Polish :nail_care:

#352 Translations update from Weblate
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Polish :nail_care:

#344 make light teaser option use the original image
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/teaserEditPanel.tsx
Labels: PR: Polish :nail_care:

#332 wpc-458-highlight-pending-articles-and-pages
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Polish :nail_care:

#347 Extending elements in API
  packages/api/src/graphql/richText.ts
Labels: PR: New Feature :heart:

#351 F/wpc-482-publication-date-without-seconds
  packages/editor/package.json
  packages/editor/src/client/base.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/imageEditPanel.tsx
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/teaserSelectPanel.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/authorList.tsx
  packages/editor/src/client/routes/commentList.tsx
  packages/editor/src/client/routes/pageEditor.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/routes/userList.tsx
  yarn.lock
Labels: PR: Polish :nail_care:

#331 image cta on website
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/types.ts
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
Labels: PR: New Feature :heart:

#358 F/wpc 482 format date with fns
  packages/editor/package.json
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  yarn.lock
Labels: PR: Polish :nail_care:

#337 Get rid of @ts-ignore
  examples/website/webpack.config.ts
  packages/api-db-mongodb/src/db/invoice.ts
  packages/api/src/server.ts
  packages/editor/__mocks__/react-i18next.ts
  packages/editor/package.json
  packages/editor/src/client/authContext.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/routes/imageList.tsx
  yarn.lock
Labels: PR: Internal :house:

#365 f/499-translation-rsuite-js
  packages/editor/src/client/app.tsx
  packages/editor/src/client/atoms/addBlockInput.tsx
  packages/editor/src/client/blocks/blockMap.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/locales/rsuiteDe.ts
  packages/editor/src/client/locales/rsuiteFr.ts
Labels: PR: Polish :nail_care:

#348 add my peer info page
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/peerList.tsx
Labels: PR: Polish :nail_care:

#346 keyboard date input
  packages/api/src/error.ts
  packages/editor/package.json
  packages/editor/src/client/atoms/dateTimePicker.less
  packages/editor/src/client/atoms/dateTimePicker.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/routes/imageList.tsx
  yarn.lock
Labels: PR: New Feature :heart:

#369 F/wpc 524 color picker peered articles color
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
Labels: PR: Polish :nail_care:

#370 user and session improvements
  examples/api/src/index.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/session.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/private/user.graphql
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/user.ts
  packages/api/__tests__/utility.ts
  packages/api/src/db/session.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/user.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/panel/userEditPanel.tsx
Labels: PR: New Feature :heart:

#374 mapping metadata properties to get rid of __typename
  packages/editor/src/client/panel/userEditPanel.tsx
Labels: PR: Bug Fix :bug:
