Repository wepublish/wepublish, pull requests merged in 2021-04, with the labels that each got.

#231 Always set updatedAt and publishedAt date
  packages/api/src/graphql/query.public.ts
Labels: PR: Bug Fix :bug:

#232 b/wpc-322-make-member-plans-visually-deleted
  packages/editor/src/client/routes/memberPlanList.tsx
Labels: PR: Bug Fix :bug:

#233 wpc-286-image-updated-alert
  packages/editor/src/client/panel/imageEditPanel.tsx
Labels: PR: Bug Fix :bug:

#234 wpc-305-change-unpublish-icon
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Bug Fix :bug:

#237 enh. installation troubleshooting documentation
  FAQ.md
Labels: PR: Docs :memo:

#241 changed sorting to be with modification date
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: New Feature :heart:

#239 Highlight link button
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/atoms/toolbar.tsx
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
Labels: PR: Polish :nail_care:

#238 F/wpc 323 sorting pagination author list
  packages/api-db-mongodb/src/db/author.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/src/db/author.ts
  packages/api/src/graphql/author.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/src/client/api/author.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/authorList.tsx
Labels: PR: New Feature :heart:

#243 remove extra lead field from teaser panel
  packages/editor/src/client/panel/teaserEditPanel.tsx
Labels: PR: Bug Fix :bug:

#242 add spacing to layout of forms in Navigation panel
  packages/editor/src/client/panel/navigationEditPanel.tsx
Labels: PR: Polish :nail_care:

#230 split time and date picker
  packages/editor/src/client/atoms/dateTimePicker.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
Labels: PR: Polish :nail_care:

#240 f/wpc-320-create-an-author-in-the-article-metadata
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/authorCheckPicker.tsx
Labels: PR: New Feature :heart:

#244 Fix escaping regex
  packages/api-db-mongodb/src/db/article.ts
  packages/api-db-mongodb/src/db/author.ts
  packages/api-db-mongodb/src/db/image.ts
  packages/api-db-mongodb/src/db/invoice.ts
  packages/api-db-mongodb/src/db/mailLog.ts
  packages/api-db-mongodb/src/db/memberPlan.ts
  packages/api-db-mongodb/src/db/page.ts
  packages/api-db-mongodb/src/db/payment.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/db/userRole.ts
  packages/api-db-mongodb/src/utility.ts
Labels: PR: Bug Fix :bug:

#247 Proper check if the path includes login or logout
  packages/editor/src/client/index.tsx
Labels: PR: Bug Fix :bug:

#253 added time in modefied coloumn
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: New Feature :heart:

#252 Comment list color
  packages/editor/src/client/global.less
  packages/editor/src/client/routes/commentList.tsx
Labels: PR: Polish :nail_care:
