Repository wepublish/wepublish, pull requests merged in 2021-12, with the labels that each got.

#431 Make public jwt expiry time ajustable
  config/create-gke-manifest.js
  packages/api/src/context.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
Labels: PR: Internal :house:

#433 Use mailproviders with templates
  packages/api/__tests__/specs/mailchimpMailProvider.ts
  packages/api/src/mails/MailchimpMailProvider.ts
  packages/api/src/mails/MailgunMailProvider.ts
Labels: PR: New Feature :heart:

#430 Improved memberPlans with slugs
  packages/api-db-mongodb/src/db/memberPlan.ts
  packages/api/src/context.ts
  packages/api/src/db/memberPlan.ts
  packages/api/src/error.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
Labels: PR: New Feature :heart:

#434 use SEND_LOGIN_JWT_EXPIRES_MIN for sendWebsiteLogin
  packages/api/src/graphql/mutation.private.ts
Labels: PR: Internal :house:

#436 payment method with slugs
  packages/api-db-mongodb/src/db/paymentMethod.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api-db-mongodb/src/utility.ts
  packages/api/src/context.ts
  packages/api/src/db/paymentMethod.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/payment.ts
  packages/api/src/graphql/paymentMethod.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/paymentMethod.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
  packages/editor/src/client/panel/paymentMethodEditPanel.tsx
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#440 implemented a quick fix for failed registrations
  packages/api/src/error.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/utility.ts
Labels: PR: Internal :house:

#441 Add invoice email to payrexx create gateway request
  packages/api/src/payments/payrexxPaymentProvider.ts
Labels: PR: Polish :nail_care:

#450 Updated editor graphql codegen api
  packages/editor/src/client/api/index.ts
Labels: PR: Internal :house:

#452 added oauth2Accounts to the GraphQLUser
  packages/api/src/graphql/user.ts
  packages/editor/src/client/api/index.ts
Labels: PR: New Feature :heart:

#455 make the mailgun from.submit use https
  packages/api/src/mails/MailgunMailProvider.ts
Labels: PR: Bug Fix :bug:

#449 Some subscription changes
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/memberContext.ts
  packages/api/src/utility.ts
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#451 catch stripe errors and send mail
  examples/api/src/index.ts
  examples/api/templates/emails/memberSubscriptionPayment/offSessionPaymentFailed/html.pug
  examples/api/templates/emails/memberSubscriptionPayment/offSessionPaymentFailed/subject.pug
  packages/api/src/mails/mailContext.ts
  packages/api/src/memberContext.ts
  packages/api/src/payments/paymentProvider.ts
  packages/api/src/payments/stripePaymentProvider.ts
Labels: PR: New Feature :heart:

#458 better logging
  packages/api/src/payments/payrexxPaymentProvider.ts
Labels: PR: Internal :house:

#462 encode all url parameters that are sent with node-fetch
  packages/api/src/payments/payrexxPaymentProvider.ts
Labels: PR: Bug Fix :bug:

#463 only send custom_missing mail to offSession payments
  packages/api/src/memberContext.ts
Labels: PR: Bug Fix :bug:

#464 Stripe improvements
  packages/api/src/payments/stripePaymentProvider.ts
Labels: PR: Internal :house:

#468 tiny fixes
  examples/api/src/index.ts
  packages/api/src/events.ts
  packages/api/src/mails/MailgunMailProvider.ts
  packages/api/src/server.ts
Labels: PR: Bug Fix :bug:

#469 Member context improvements
  examples/api/src/index.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/jobs.ts
  packages/api/src/memberContext.ts
  packages/api/src/payments/paymentProvider.ts
Labels: PR: New Feature :heart:, PR: Internal :house:

#460 F/wpc-585-pagination-image-library
  packages/api-db-mongodb/src/db/image.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/src/client/api/image.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/imageList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Polish :nail_care:

#473 bug fix for checking invoice states
  packages/api/src/memberContext.ts
Labels: PR: Bug Fix :bug:
