Repository wepublish/wepublish, pull requests merged in 2022-10, with the labels that each got.

#687 Docker builds, entrypoints improvements
  .dockerignore
  .github/workflows/deploy-pull-request.yml
  .github/workflows/deploy-to-k8s.yml
  .github/workflows/publish-docker-image.yml
  .github/workflows/publish-docker-images.yml
  .github/workflows/publish-master-artifacts.yml
  .github/workflows/publish-release-artifacts.yml
  Dockerfile
  config/create-gke-manifest.js
  config/notify-github.js
  config/notify-jira.js
  docker-compose.yml
  examples/api/bin/run-server.js
  examples/api/package.json
  examples/api/src/index.ts
  examples/oauth2/bin/run-server.js
  examples/oauth2/package.json
  examples/oauth2/src/index.ts
  examples/website/bin/run-server.js
  examples/website/package.json
  examples/website/src/server/index.ts
  examples/website/src/server/server.ts
  examples/website/tsconfig.json
  helm/charts/wepublish/Chart.yaml
  helm/charts/wepublish/templates/deployment-api.yaml
  helm/charts/wepublish/templates/deployment-editor.yaml
  package.json
  packages/api/package.json
  packages/api/prisma/run-seed.ts
  packages/api/src/runServer.ts
  packages/editor/bin/run-server.js
  packages/editor/package.json
  packages/editor/src/server/index.tsx
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: Internal :house:

#719 WPC-812-update-userprefered-name-empty-string
  packages/api/src/validator.ts
Labels: PR: Bug Fix :bug:

#707 chore: add git hooks to rebuild prisma when switching or merging branches
  package.json
Labels: PR: Internal :house:

#736 docs: document prisma migrate reset
  FAQ.md
Labels: PR: Docs :memo:

#738 test(editor): got rid of ptest and ran eslint fix
  packages/editor/__tests__/specs/__snapshots__/elements.test.ts.snap
  packages/editor/__tests__/specs/__snapshots__/normalizing.test.ts.snap
  packages/editor/__tests__/specs/authorEditPanel.tsx
  packages/editor/__tests__/specs/elements.test.ts
  packages/editor/__tests__/specs/i18n.test.tsx
  packages/editor/__tests__/specs/normalizing.test.ts
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/__tests__/specs/tokenGeneratePanel.tsx
  packages/editor/__tests__/specs/unsavedChangesDialog.test.tsx
  packages/editor/__tests__/specs/userEditView.tsx
  packages/editor/__tests__/specs/userRoleEditPanel.tsx
  packages/editor/__tests__/utils.ts
Labels: PR: Internal :house:

#737 feat(api): add relations to revision images
  packages/api/prisma/migrations/20221025091043_revisions_image_references/migration.sql
  packages/api/prisma/schema.prisma
Labels: PR: New Feature :heart:

#733 feat(api): allow sorting of comments by rating
  packages/api/package.json
  packages/api/src/db/comment.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/comment/comment.public-queries.ts
  packages/api/src/graphql/comment/comment.ts
  packages/api/src/graphql/query.public.ts
  yarn.lock
Labels: PR: New Feature :heart:
