Repository wepublish/wepublish, pull requests merged in 2022-08, with the labels that each got.

#649 fix(editor): editing peers required the token by accident
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/toggleRequiredLabel.test.ts.snap
  packages/editor/__tests__/specs/toggleRequiredLabel.test.ts
  packages/editor/src/client/atoms/user/editUserPassword.tsx
  packages/editor/src/client/panel/authorEditPanel.tsx
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
  packages/editor/src/client/panel/paymentMethodEditPanel.tsx
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
  packages/editor/src/client/panel/subscriptionEditPanel.tsx
  packages/editor/src/client/panel/userRoleEditPanel.tsx
  packages/editor/src/client/routes/userEditView.tsx
  packages/editor/src/client/toggleRequiredLabel.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#661 fix(api): userlist filter missing address filter due to merge conflict
  packages/api/src/graphql/user/user.queries.ts
Labels: PR: Bug Fix :bug:

#662 docker compose fix
  package.json
Labels: PR: Bug Fix :bug:, PR: Internal :house:

#650 chore: add recommended vscode plugins
  .vscode/extensions.json
Labels: PR: Internal :house:

#654 fix(api): challenge validUntil should be a date
  packages/api/src/challenges/algebraicCaptchaChallenge.ts
  packages/api/src/challenges/challengeProvider.ts
  packages/api/src/graphql/challenge.ts
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:

#672 fix(api): navigation link missing relations
  packages/api/__tests__/specs/__snapshots__/navigation.ts.snap
  packages/api/__tests__/specs/navigation.ts
  packages/api/prisma/migrations/20220823071824_add_relations_navigationlink/migration.sql
  packages/api/prisma/schema.prisma
  yarn.lock
Labels: PR: Bug Fix :bug:

#677 Add WePublish helm chart
  helm/charts/app/Chart.yaml
  helm/charts/app/templates/_helpers.tpl
  helm/charts/app/templates/deployment-api.yaml
  helm/charts/app/templates/deployment-editor.yaml
  helm/charts/app/templates/ingress.yaml
  helm/charts/app/templates/secrets.yaml
  helm/charts/app/templates/service.yml
  helm/charts/app/values.yaml
Labels: PR: Internal :house:

#665 Build and push image on new tag
  .github/workflows/npm-publish-on-tags.yml
  .github/workflows/publish-on-tags.yml
Labels: PR: Internal :house:

#676 ci: fix deployment action if jira issue not found
  config/notify-jira.js
Labels: PR: Internal :house:

#659 feat(editor): disable preview for article/page without draft
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Bug Fix :bug:
