Repository wepublish/wepublish, pull requests merged in 2022-02, with the labels that each got.

#484 export csv for users with subscriptions
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/utility.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/ExportSubscriptionsCsvModal.tsx
  packages/editor/src/client/routes/userList.tsx
Labels: PR: New Feature :heart:

#503 bug fix for user.subscription.deactivation filters
  packages/api-db-mongodb/src/db/user.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/memberContext.ts
Labels: bug, PR: Breaking Change :boom:

#504 improved database migration
  packages/api-db-mongodb/src/migration.ts
Labels: bug

#500 generate loginURL for mails
  examples/api/src/index.ts
  examples/api/templates/emails/memberSubscriptionPayment/offSessionPaymentOneWeekBefore/html.pug
  examples/api/templates/emails/memberSubscriptionPayment/onSessionAfter/html.pug
  examples/api/templates/emails/memberSubscriptionPayment/onSessionBefore/html.pug
  packages/api/src/context.ts
  packages/api/src/jobs.ts
  packages/api/src/memberContext.ts
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#490 Article/Page public URL in editor page
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/page.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: New Feature :heart:

#491 resolve auto open gallery on save
  packages/editor/src/client/blocks/imageGalleryBlock.tsx
Labels: PR: Bug Fix :bug:

#505 Save flex teaser of page and peer
  packages/editor/src/client/blocks/types.ts
Labels: PR: Bug Fix :bug:

#493 f/wpc-611-improve-publication-behavior
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/atoms/dateTimePicker.tsx
  packages/editor/src/client/global.less
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Polish :nail_care:

#513 fixed csv export
  packages/api/src/utility.ts
Labels: bug

#514 release 3.0.0 hot fixes
  packages/api-db-mongodb/src/db/article.ts
  packages/api-db-mongodb/src/db/page.ts
  packages/editor/src/client/panel/publishArticlePanel.tsx
  packages/editor/src/client/panel/publishPagePanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: bug

#497 karma media additional url
  config/create-gke-manifest.js
  docker-compose.yml
  examples/api/src/index.ts
  packages/api-media-karma/__tests__/specs/index.ts
  packages/api-media-karma/src/index.ts
  packages/api/__tests__/utility.ts
Labels: PR: Internal :house:
