Repository wepublish/wepublish, pull requests merged in 2022-01, with the labels that each got.

#478 Fix typos in i18n
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Internal :house:

#480 Remove mail hardcoded mail
  examples/api/src/index.ts
Labels: PR: Polish :nail_care:

#481 F/wpc 605 preview publish tooltip
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Polish :nail_care:

#483 f/wpc-600 preview link
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Polish :nail_care:

#403 flex teaser block
  examples/website/src/shared/blocks/blockRenderer.tsx
  examples/website/src/shared/blocks/flexGridBlock.tsx
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/types.ts
  packages/api/src/db/block.ts
  packages/api/src/graphql/blocks.ts
  packages/api/src/graphql/mutation.private.ts
  packages/editor/package.json
  packages/editor/src/client/api/block.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/blocks/blockMap.tsx
  packages/editor/src/client/blocks/teaserGridBlock.tsx
  packages/editor/src/client/blocks/teaserGridFlexBlock.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/en.json
  yarn.lock
Labels: PR: New Feature :heart:

#475 more detailed deactivation
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/user.ts
  packages/api/src/jobs.ts
  packages/api/src/memberContext.ts
  packages/editor/package.json
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionDeactivatePanel.tsx
  packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
Labels: PR: New Feature :heart:

#494 duplicate pending article/page
  packages/api/src/graphql/mutation.private.ts
Labels: PR: Bug Fix :bug:
