Repository wepublish/wepublish, pull requests merged in 2022-12, with the labels that each got.

#728 Remove Oauth2 service, example, package
  config/create-gke-manifest.js
  docker-compose.yml
  examples/api/.env.example
  examples/api/src/index.ts
  examples/oauth2/.env.example
  examples/oauth2/bin/run-server.js
  examples/oauth2/customViews/_layout.ejs
  examples/oauth2/customViews/interaction.ejs
  examples/oauth2/customViews/login.ejs
  examples/oauth2/customViews/repost.ejs
  examples/oauth2/customViews/select_account.ejs
  examples/oauth2/nodemon.json
  examples/oauth2/package.json
  examples/oauth2/src/index.ts
  examples/oauth2/src/tsconfig.json
  package.json
  packages/api/src/runServer.ts
  packages/oauth2/.npmignore
  packages/oauth2/index.d.ts
  packages/oauth2/index.js
  packages/oauth2/package.json
  packages/oauth2/src/adapter.ts
  packages/oauth2/src/configuration.ts
  packages/oauth2/src/index.tsx
  packages/oauth2/src/migrations.ts
  packages/oauth2/src/routes.ts
  packages/oauth2/src/schema/0.ts
  packages/oauth2/src/schema/index.ts
  packages/oauth2/src/server.ts
  packages/oauth2/src/tsconfig.json
  packages/oauth2/views/_layout.ejs
  packages/oauth2/views/interaction.ejs
  packages/oauth2/views/login.ejs
  packages/oauth2/views/repost.ejs
  packages/oauth2/views/select_account.ejs
Labels: PR: Internal :house:

#700 F/wpc 880 add comment context
  packages/api/__tests__/api/private/index.ts
  packages/api/prisma/schema.prisma
  packages/api/src/db/comment.ts
  packages/api/src/graphql/blocks.ts
  packages/api/src/graphql/comment/comment.private-mutation.ts
  packages/api/src/graphql/comment/comment.private-queries.ts
  packages/api/src/graphql/comment/comment.public-queries.ts
  packages/api/src/graphql/comment/comment.queries.ts
  packages/api/src/graphql/comment/comment.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/atoms/comment/commentHistory.tsx
  packages/editor/src/client/atoms/comment/commentPreview.tsx
  packages/editor/src/client/atoms/comment/commentStateDropdown.tsx
  packages/editor/src/client/atoms/comment/commentUser.tsx
  packages/editor/src/client/atoms/comment/createCommentBtn.tsx
  packages/editor/src/client/atoms/searchAndFilter/userSearch.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/comments/commentEditView.tsx
  packages/editor/src/client/routes/comments/commentList.tsx
Labels: PR: New Feature :heart:

#770 fix(api): slugs and titles of pages to be nullable
  packages/api/__tests__/api/private/index.ts
  packages/api/src/graphql/page.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/blocks/teaserGridBlock.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
  packages/editor/src/client/panel/teaserEditPanel.tsx
  packages/editor/src/client/routes/pageEditor.tsx
Labels: PR: Bug Fix :bug:

#779 feat(editor/api): implemented the event block
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/specs/__snapshots__/event.ts.snap
  packages/api/__tests__/specs/event.ts
  packages/api/src/context.ts
  packages/api/src/db/block.ts
  packages/api/src/graphql/blocks.ts
  packages/api/src/graphql/event/event.private-mutation.ts
  packages/api/src/graphql/event/event.queries.ts
  packages/api/src/graphql/event/event.ts
  packages/api/src/graphql/mutation.private.ts
  packages/editor/src/client/api/block.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/atoms/tag/selectTags.tsx
  packages/editor/src/client/blocks/blockMap.tsx
  packages/editor/src/client/blocks/eventBlock.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/selectEventsPanel.tsx
  packages/editor/src/client/routes/events/eventCreateView.tsx
  packages/editor/src/client/routes/events/eventEditView.tsx
Labels: PR: New Feature :heart:
