Repository wepublish/wepublish, pull requests merged in 2022-09, with the labels that each got.

#688 Move api-media-karma into api package
  examples/api/src/index.ts
  package.json
  packages/api-media-karma/.npmignore
  packages/api-media-karma/CHANGELOG.md
  packages/api-media-karma/__tests__/setup.ts
  packages/api-media-karma/index.d.ts
  packages/api-media-karma/index.js
  packages/api-media-karma/jest.config.js
  packages/api-media-karma/package.json
  packages/api-media-karma/src/tsconfig.json
  packages/api/__tests__/specs/mediaAdapter.ts
  packages/api/__tests__/test.jpg
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/index.ts
  packages/api/src/media/karmaMediaAdapter.ts
  packages/api/src/media/mediaAdapter.ts
  packages/api/src/runServer.ts
Labels: PR: Breaking Change :boom:, PR: Internal :house:

#686 Recognized Metadata if image is uploaded direct via article or page
  packages/editor/src/client/atoms/imageMetaData.tsx
  packages/editor/src/client/panel/imageEditPanel.tsx
  packages/editor/src/client/panel/imageSelectPanel.tsx
  packages/editor/src/client/panel/imageUploadAndEditPanel.tsx
Labels: PR: Bug Fix :bug:

#673 feat(api): allow admins to create and edit comments
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/prisma/schema.prisma
  packages/api/src/graphql/comment/comment.private-mutation.ts
  packages/api/src/graphql/comment/comment.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/permissions.ts
Labels: PR: New Feature :heart:

#681 feat(editor): UI for editing a comment
  packages/api/src/graphql/comment/comment.private-mutation.ts
  packages/api/src/graphql/comment/comment.private-queries.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/tag/tag.private-query.ts
  packages/api/src/graphql/tag/tag.ts
  packages/editor/src/client/api/comment.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/app.tsx
  packages/editor/src/client/atoms/modelTitle.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/comments/commentEditView.tsx
  packages/editor/src/client/routes/comments/commentList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: New Feature :heart:

#693 Fix mount path for postgres pvc
  config/create-gke-manifest.js
Labels: PR: Bug Fix :bug:

#667 feat: add polls
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/prisma/migrations/20220819145134_create_poll/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/db/user.ts
  packages/api/src/error.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/poll/poll.private-mutation.ts
  packages/api/src/graphql/poll/poll.private-queries.ts
  packages/api/src/graphql/poll/poll.public-mutation.ts
  packages/api/src/graphql/poll/poll.public-queries.ts
  packages/api/src/graphql/poll/poll.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/poll.graphql
  packages/editor/src/client/app.tsx
  packages/editor/src/client/atoms/modelTitle.tsx
  packages/editor/src/client/atoms/poll/createPollBtn.tsx
  packages/editor/src/client/atoms/poll/deletePollModal.tsx
  packages/editor/src/client/atoms/poll/pollAnswers.tsx
  packages/editor/src/client/atoms/poll/pollExternalVotes.tsx
  packages/editor/src/client/atoms/poll/pollStateIndication.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/polls/pollEditView.tsx
  packages/editor/src/client/routes/polls/pollList.tsx
  yarn.lock
Labels: PR: New Feature :heart:

#690 WPC-841 wrong user subscription text
  packages/editor/src/client/atoms/user/userSubscriptionsList.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Bug Fix :bug:

#689 Prevent canceled invoices from marked as paid
  packages/api/src/graphql/invoice.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/invoice.graphql
  packages/editor/src/client/atoms/blockList.tsx
  packages/editor/src/client/atoms/invoice.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/blocks/embedBlock.tsx
  packages/editor/src/client/blocks/embeds/bildwurfAd.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/embedEditPanel.tsx
  packages/editor/src/client/panel/subscriptionEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionDeactivatePanel.tsx
  packages/editor/src/client/routes/articleList.tsx
Labels: PR: Bug Fix :bug:

#695 ci: use init containers to fix permissions of postgres volume
  config/create-gke-manifest.js
Labels: PR: Internal :house:

#694 feat(api/editor): implement a comment rating system
  examples/api/prisma/seed.ts
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/package.json
  packages/api/prisma/migrations/20220907134331_create_comment_rating/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/db/user.ts
  packages/api/src/error.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/comment-rating/comment-rating.private-mutation.ts
  packages/api/src/graphql/comment-rating/comment-rating.public-mutation.ts
  packages/api/src/graphql/comment-rating/comment-rating.public-queries.ts
  packages/api/src/graphql/comment-rating/comment-rating.ts
  packages/api/src/graphql/comment/comment.public-queries.ts
  packages/api/src/graphql/comment/comment.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/editor/package.json
  packages/editor/src/client/api/comment-rating.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/app.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/commentRatingEditView.tsx
  yarn.lock
Labels: PR: New Feature :heart:

#706 feat(api/editor): implement comment and poll blocks
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/types.ts
  packages/api/src/context.ts
  packages/api/src/db/block.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/blocks.ts
  packages/api/src/graphql/comment/comment.queries.ts
  packages/api/src/graphql/comment/comment.ts
  packages/api/src/graphql/poll/poll.public-queries.ts
  packages/api/src/mails/mailProvider.ts
  packages/api/src/utility.ts
  packages/editor/src/client/api/block.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/atoms/blockList.tsx
  packages/editor/src/client/atoms/poll/deletePollModal.tsx
  packages/editor/src/client/atoms/poll/pollStateIndication.tsx
  packages/editor/src/client/atoms/tag/selectTags.tsx
  packages/editor/src/client/blocks/blockMap.tsx
  packages/editor/src/client/blocks/commentBlock.tsx
  packages/editor/src/client/blocks/htmlBlock.tsx
  packages/editor/src/client/blocks/pollBlock.tsx
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/selectCommentsPanel.tsx
  packages/editor/src/client/panel/selectPollPanel.tsx
  packages/editor/src/client/routes/articleEditor.tsx
  packages/editor/src/client/routes/comments/commentEditView.tsx
  packages/editor/src/client/routes/comments/commentList.tsx
  packages/editor/src/client/routes/polls/pollList.tsx
Labels: PR: New Feature :heart:

#708 feat(api): user votes/rating api
  packages/api/prisma/seed.ts
  packages/api/src/db/setting.ts
  packages/api/src/error.ts
  packages/api/src/graphql/comment-rating/comment-rating.public-mutation.ts
  packages/api/src/graphql/comment-rating/comment-rating.public-queries.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/poll/poll.public-mutation.ts
  packages/api/src/graphql/poll/poll.public-queries.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/graphql/setting.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/settingList.tsx
Labels: PR: New Feature :heart:

#710 fix(api): only query published peer articles
  packages/api/src/graphql/peer-article/peer-article.private-queries.ts
Labels: PR: Internal :house:

#678 Release helm chart to helm repository
  .github/workflows/release-helm-chart.yml
  helm/charts/wepublish/Chart.yaml
  helm/charts/wepublish/templates/_helpers.tpl
  helm/charts/wepublish/templates/deployment-api.yaml
  helm/charts/wepublish/templates/deployment-editor.yaml
  helm/charts/wepublish/templates/ingress.yaml
  helm/charts/wepublish/templates/secrets.yaml
  helm/charts/wepublish/templates/service.yml
  helm/charts/wepublish/values.yaml
Labels: PR: Internal :house:

#702 WPC-696 integrate payrexx subscription provider
  config/create-gke-manifest.js
  examples/api/.env.example
  examples/api/src/index.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/index.ts
  packages/api/src/memberContext.ts
  packages/api/src/payments/paymentProvider.ts
  packages/api/src/payments/payrexxSubscriptionPaymentProvider.ts
Labels: PR: New Feature :heart:

#714 Added missing yargs module to api package
  packages/api/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#715 Fix payment provider period start date
  packages/api/src/payments/payrexxSubscriptionPaymentProvider.ts
Labels: PR: Bug Fix :bug:
