Repository wepublish/wepublish, pull requests merged in 2022-03, with the labels that each got.

#525 display action buttons
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
Labels: PR: Polish :nail_care:

#518 send next invoice reminder fix
  packages/api/src/memberContext.ts
Labels: PR: Bug Fix :bug:

#523 F/wpc 620 peered articles list
  packages/api/__tests__/api/private/index.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/src/client/api/article.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/app.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/global.less
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/teaserSelectPanel.tsx
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/peerArticleList.tsx
Labels: PR: New Feature :heart:

#530 preview own peer profile
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
  packages/editor/src/client/routes/peerList.tsx
Labels: PR: Polish :nail_care:

#526 F/wpc 639 filter memberplans by tags
  packages/api-db-mongodb/src/db/memberPlan.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api/src/db/memberPlan.ts
  packages/api/src/graphql/memberPlan.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/memberPlan.graphql
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
Labels: PR: Polish :nail_care:

#536 bug fix in memberplans
  packages/api/src/graphql/memberPlan.ts
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
Labels: PR: Bug Fix :bug:

#537 F/wpc 620 translation fix
  packages/editor/src/client/base.tsx
Labels: PR: Polish :nail_care:

#541 F/wpc 656 user details
  packages/api/src/graphql/mutation.public.ts
Labels: PR: Polish :nail_care:

#547 added sandbox property to iframe
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/types.ts
  packages/api/__tests__/api/private/block.graphql
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/block.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/fakePeerAdminSchema.json
  packages/api/__tests__/specs/__snapshots__/page.ts.snap
  packages/api/src/db/block.ts
  packages/api/src/graphql/blocks.ts
  packages/editor/src/client/api/block.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/blocks/embedBlock.tsx
  packages/editor/src/client/blocks/embeds/iframe.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/panel/embedEditPanel.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Polish :nail_care:

#542 WPC-608: As an user i want to comment without authentication
  config/create-gke-manifest.js
  examples/api/.env.example
  examples/api/src/index.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/utility.ts
  packages/api/package.json
  packages/api/src/challenges/algebraicCaptchaChallenge.ts
  packages/api/src/challenges/challengeProvider.ts
  packages/api/src/context.ts
  packages/api/src/db/comment.ts
  packages/api/src/error.ts
  packages/api/src/graphql/challenge.ts
  packages/api/src/graphql/comment.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/index.ts
  packages/editor/src/client/api/comment.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/commentList.tsx
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#540 b/WPC-655: As a publisher, i want mailto-Links without slashes (//)
  packages/editor/src/client/blocks/richTextBlock/toolbar/linkMenu.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
Labels: PR: Bug Fix :bug:
