Repository wepublish/wepublish, pull requests merged in 2022-04, with the labels that each got.

#556 f/WPC-674 Introduce firstname to user
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/types.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
  packages/api/src/db/user.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/user.ts
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/__tests__/specs/userEditPanel.tsx
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/routes/userList.tsx
Labels: PR: New Feature :heart:

#560 chore(reviews): add CODEOWNERS file
  CODEOWNERS
Labels: PR: Internal :house:

#561 chore(ci/cd): use GCLOUD_PROJECT_ID, GCLOUD_AUTH_KEY secrets only
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/pr_close.yml
Labels: PR: Internal :house:

#543 f/wpc-636 - currency in franken
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/atoms/currencyInput.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
Labels: PR: New Feature :heart:, PR: Polish :nail_care:

#533 added env variables to .env.example files
  examples/api/.env.example
  packages/api/.env.example
Labels: PR: Docs :memo:

#554 Improve builds
  .github/workflows/deploy.yml
  dockerfile
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionEditPanel.tsx
Labels: PR: Internal :house:

#539 Payload too large
  packages/api/src/server.ts
  packages/api/src/utility.ts
Labels: PR: Bug Fix :bug:

#516 export event emitters
  examples/api/src/index.ts
  packages/api/src/index.ts
Labels: PR: New Feature :heart:

#562 chore(releases): semi automated releases
  .github/workflows/npm-publish-on-tags.yml
  config/release.sh
Labels: PR: Internal :house:

#563 Fix npm release on tags
  .github/workflows/npm-publish-on-tags.yml
Labels: PR: Bug Fix :bug:

#555 adjust choose image panel image size
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/src/client/atoms/chooseEditImage.tsx
  packages/editor/src/client/atoms/placeholderInput.tsx
  packages/editor/src/client/panel/peerEditPanel.tsx
Labels: PR: Bug Fix :bug:

#545 WPC-657: As a publisher, when uploading an image, i want the metadata automatically captured
  examples/website/src/shared/route/gqlFragments.ts
  packages/api-db-mongodb/src/db/image.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/api/private/image.graphql
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/image.graphql
  packages/api/__tests__/api/public/index.ts
  packages/api/__tests__/fakePeerAdminSchema.json
  packages/api/src/db/image.ts
  packages/api/src/graphql/image.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/query.private.ts
  packages/editor/package.json
  packages/editor/src/client/api/image.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/panel/imageEditPanel.tsx
  packages/editor/src/client/panel/imageUploadAndEditPanel.tsx
  packages/editor/src/client/panel/imageUploadPanel.tsx
  packages/editor/src/client/panel/teaserSelectPanel.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/routes/subscriptionList.tsx
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/utility.ts
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#568 WPC-686-Wrong auto-generated Maybe-Tags
  packages/api-db-mongodb/src/db/memberPlan.ts
  packages/api/src/db/memberPlan.ts
  packages/api/src/graphql/memberPlan.ts
  packages/editor/src/client/api/index.ts
Labels: PR: Bug Fix :bug:
