Repository wepublish/wepublish, pull requests merged in 2022-07, with the labels that each got.

#628 Normalized and validated mail on create and update
  packages/api-db-mongodb/package.json
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/validator.ts
  yarn.lock
Labels: enhancement

#625 b/WPC-765-auto-renew
  docs/README.md
  examples/api/.env.example
  packages/api/.env.example
  packages/api/src/memberContext.ts
Labels: bug, enhancement

#634 B/wpc 770 cancel invoices when deactivating subscription
  docs/README.md
  examples/api/.env.example
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/memberContext.ts
Labels: PR: Bug Fix :bug:

#637 Settings page
  packages/api-db-mongodb/src/adapter.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/setting.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/__tests__/specs/__snapshots__/user.ts.snap
  packages/api/__tests__/specs/__snapshots__/userRole.ts.snap
  packages/api/src/context.ts
  packages/api/src/db/adapter.ts
  packages/api/src/db/setting.ts
  packages/api/src/error.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/permissions.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/setting.ts
  packages/api/src/index.ts
  packages/api/src/memberContext.ts
  packages/api/src/utility.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/setting.graphql
  packages/editor/src/client/app.tsx
  packages/editor/src/client/base.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/route.tsx
  packages/editor/src/client/routes/settingList.tsx
Labels: PR: New Feature :heart:

#635 Preview page with token or slug
  packages/api/src/graphql/query.public.ts
Labels: PR: Bug Fix :bug:
