Repository wepublish/wepublish, pull requests merged in 2022-06, with the labels that each got.

#613 test(editor): replace enzyme with @testing-library/react to fix tests
  packages/editor/__tests__/setup.ts
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/tokenGeneratePanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userRoleEditPanel.tsx.snap
  packages/editor/__tests__/specs/authorEditPanel.tsx
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/__tests__/specs/tokenGeneratePanel.tsx
  packages/editor/__tests__/specs/unsavedChangesDialog.test.tsx
  packages/editor/__tests__/specs/userEditPanel.tsx
  packages/editor/__tests__/specs/userRoleEditPanel.tsx
  packages/editor/__tests__/utils.ts
  packages/editor/jest.config.js
  packages/editor/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#605 fix: bring back filters (paidUntil and startsAt)
  packages/api-db-mongodb/src/db/subscription.ts
  packages/api/src/graphql/subscription.ts
  packages/editor/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#602 WPC-728 tmp user bug
  packages/api-db-mongodb/src/migration.ts
Labels: PR: Bug Fix :bug:

#612 fix: autoRenew filter
  packages/editor/src/client/routes/subscriptionList.tsx
Labels: PR: Bug Fix :bug:

#590 WPC-665 set paidAt manually (invoice history)
  DOCUMENTATION.md
  README.md
  docs/README.md
  packages/api-db-mongodb/src/adapter.ts
  packages/api-db-mongodb/src/db/invoice.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/invoice.ts
  packages/api/src/graphql/invoice.ts
  packages/api/src/payments/paymentProvider.ts
  packages/editor/src/client/api/generalFragments.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/invoice.graphql
  packages/editor/src/client/api/user.graphql
  packages/editor/src/client/atoms/invoice.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/invoiceListPanel.tsx
  packages/editor/src/client/panel/subscriptionEditPanel.tsx
  packages/editor/src/client/route.tsx
Labels: PR: New Feature :heart:

#611 fix(editor): pagination translation broken and max pages
  packages/editor/src/client/locales/rsuiteDe.ts
  packages/editor/src/client/locales/rsuiteFr.ts
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/authorList.tsx
  packages/editor/src/client/routes/commentList.tsx
  packages/editor/src/client/routes/imageList.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/routes/peerArticleList.tsx
  packages/editor/src/client/routes/subscriptionList.tsx
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Bug Fix :bug:

#598 WPC-640 Disable peer
  examples/website/src/shared/blocks/blockRenderer.tsx
  examples/website/src/shared/route/articleAdapter.ts
  examples/website/src/shared/route/blockAdapters.ts
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/route/pageTemplateContainer.tsx
  examples/website/src/shared/teasers/textTeaser.tsx
  examples/website/src/shared/types.ts
  packages/api-db-mongodb/src/db/peer.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api/__tests__/api/private/peer.graphql
  packages/api/__tests__/specs/__snapshots__/peer.ts.snap
  packages/api/src/db/peer.ts
  packages/api/src/error.ts
  packages/api/src/graphql/peer.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/query.public.ts
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/jest.config.js
  packages/editor/package.json
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/peer.graphql
  packages/editor/src/client/atoms/blockList.tsx
  packages/editor/src/client/blocks/teaserGridBlock.tsx
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/routes/peerList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: New Feature :heart:

#610 WPC 679 remove tmp user
  packages/api-db-mongodb/src/adapter.ts
  packages/api-db-mongodb/src/db/schema.ts
  packages/api-db-mongodb/src/db/tempUser.ts
  packages/api-db-mongodb/src/db/user.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/adapter.ts
  packages/api/src/db/subscription.ts
  packages/api/src/db/tempUser.ts
  packages/api/src/db/user.ts
  packages/api/src/events.ts
  packages/api/src/graphql/mutation.private.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/subscription.ts
  packages/api/src/graphql/user.ts
  packages/api/src/index.ts
  packages/api/src/memberContext.ts
  packages/api/src/payments/paymentProvider.ts
  packages/api/src/utility.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/subscriptionEditPanel.tsx
  packages/editor/src/client/routes/subscriptionList.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Breaking Change :boom:, PR: Polish :nail_care:

#565 F/wpc 667 form validation
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/peerEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userRoleEditPanel.tsx.snap
  packages/editor/__tests__/specs/authorEditPanel.tsx
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/__tests__/specs/userEditPanel.tsx
  packages/editor/__tests__/specs/userRoleEditPanel.tsx
  packages/editor/package.json
  packages/editor/src/client/atoms/blockList.tsx
  packages/editor/src/client/atoms/chooseEditImage.tsx
  packages/editor/src/client/atoms/currencyInput.tsx
  packages/editor/src/client/atoms/invoice.tsx
  packages/editor/src/client/atoms/listInput.tsx
  packages/editor/src/client/atoms/searchAndFilter/subscriptionListFilter.tsx
  packages/editor/src/client/atoms/searchAndFilter/userSearch.tsx
  packages/editor/src/client/blocks/embedBlock.tsx
  packages/editor/src/client/blocks/imageBlock.tsx
  packages/editor/src/client/blocks/imageGalleryBlock.tsx
  packages/editor/src/client/blocks/teaserGridBlock.tsx
  packages/editor/src/client/blocks/teaserGridFlexBlock.tsx
  packages/editor/src/client/global.less
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/login.tsx
  packages/editor/src/client/panel/articleMetadataPanel.tsx
  packages/editor/src/client/panel/articlePreviewLinkPanel.tsx
  packages/editor/src/client/panel/authorCheckPicker.tsx
  packages/editor/src/client/panel/authorEditPanel.tsx
  packages/editor/src/client/panel/embedEditPanel.tsx
  packages/editor/src/client/panel/galleryListEditPanel.tsx
  packages/editor/src/client/panel/imageEditPanel.tsx
  packages/editor/src/client/panel/imageSelectPanel.tsx
  packages/editor/src/client/panel/linkPageBreakEditPanel.tsx
  packages/editor/src/client/panel/memberPlanEditPanel.tsx
  packages/editor/src/client/panel/navigationEditPanel.tsx
  packages/editor/src/client/panel/pageMetadataPanel.tsx
  packages/editor/src/client/panel/pagePreviewLinkPanel.tsx
  packages/editor/src/client/panel/paymentMethodEditPanel.tsx
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/panel/peerProfileEditPanel.tsx
  packages/editor/src/client/panel/resetUserPasswordPanel.tsx
  packages/editor/src/client/panel/subscriptionEditPanel.tsx
  packages/editor/src/client/panel/teaserEditPanel.tsx
  packages/editor/src/client/panel/userCheckPicker.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/panel/userRoleEditPanel.tsx
  packages/editor/src/client/panel/userSubscriptionDeactivatePanel.tsx
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/authorList.tsx
  packages/editor/src/client/routes/commentList.tsx
  packages/editor/src/client/routes/imageList.tsx
  packages/editor/src/client/routes/memberPlanList.tsx
  packages/editor/src/client/routes/navigationList.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/routes/paymentMethodList.tsx
  packages/editor/src/client/routes/peerArticleList.tsx
  packages/editor/src/client/routes/peerList.tsx
  packages/editor/src/client/routes/tokenList.tsx
  packages/editor/src/client/routes/userList.tsx
  packages/editor/src/client/routes/userRoleList.tsx
Labels: PR: Polish :nail_care:

#594 chore: upgraded typescript to latest version
  examples/api/package.json
  examples/oauth2/package.json
  examples/website/package.json
  examples/website/src/server/render.tsx
  examples/website/src/shared/blocks/peerPageBreak.tsx
  packages/api-db-mongodb/package.json
  packages/api-media-karma/package.json
  packages/api/package.json
  packages/api/src/context.ts
  packages/api/src/graphql/mutation.public.ts
  packages/api/src/graphql/query.public.ts
  packages/api/src/mails/MailchimpMailProvider.ts
  packages/api/src/mails/mailProvider.ts
  packages/api/src/memberContext.ts
  packages/api/src/payments/paymentProvider.ts
  packages/api/src/payments/stripePaymentProvider.ts
  packages/api/src/server.ts
  packages/editor/package.json
  packages/editor/src/client/panel/peerEditPanel.tsx
  packages/editor/src/client/tsconfig.json
  packages/oauth2/package.json
  yarn.lock
Labels: PR: Breaking Change :boom:, PR: Internal :house:, Major release

#624 documentation for validation
  docs/README.md
Labels: PR: Docs :memo:
