Repository wepublish/wepublish, pull requests merged in 2022-11, with the labels that each got.

#747 fix(editor): dont show error while roles are being fetched
  packages/editor/src/client/atoms/permissionControl.tsx
Labels: PR: Bug Fix :bug:

#698 fix(api/example-website): allow peer article to have comments
  examples/api/src/index.ts
  examples/website/src/shared/molecules/commentTemplate.tsx
  examples/website/src/shared/navigation/articleFooter.tsx
  examples/website/src/shared/route/articleTemplateContainer.tsx
  examples/website/src/shared/route/footerContainer.tsx
  examples/website/src/shared/route/gqlFragments.ts
  examples/website/src/shared/types.ts
  packages/api/__tests__/utility.ts
  packages/api/prisma/migrations/20221025051208_peer_article_comments/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/error.ts
  packages/api/src/graphql/comment/comment.public-mutation.ts
  packages/api/src/graphql/comment/comment.ts
  packages/api/src/urlAdapter.ts
  packages/editor/src/client/api/index.ts
Labels: PR: New Feature :heart:

#735 feat(api,editor): extend Article, Peer Article and Page filters
  packages/api/src/db/article.ts
  packages/api/src/db/page.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/article/article.queries.ts
  packages/api/src/graphql/page.ts
  packages/api/src/graphql/page/page.queries.ts
  packages/api/src/graphql/peer-article/peer-article.private-queries.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/subscription/subscription.queries.ts
  packages/api/src/graphql/utils.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/page.graphql
  packages/editor/src/client/atoms/searchAndFilter/listViewFilters.tsx
  packages/editor/src/client/atoms/searchAndFilter/subscriptionListFilter.tsx
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/authorCheckPicker.tsx
  packages/editor/src/client/panel/teaserSelectPanel.tsx
  packages/editor/src/client/routes/articleList.tsx
  packages/editor/src/client/routes/pageList.tsx
  packages/editor/src/client/routes/peerArticleList.tsx
  packages/editor/src/client/routes/subscriptionList.tsx
Labels: PR: New Feature :heart:

#742 fix(api): authors being in a correct relational database structure
  packages/api/prisma/migrations/20221027113732_article_revisions_author_references/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/context.ts
  packages/api/src/db/article.ts
  packages/api/src/graphql/article.ts
  packages/api/src/graphql/article/article.private-mutation.ts
  packages/api/src/graphql/article/article.public-mutation.ts
  packages/api/src/graphql/article/article.public-queries.ts
  packages/api/src/graphql/article/article.queries.ts
Labels: PR: New Feature :heart:, PR: Bug Fix :bug:

#732 feat(api/editor): allow admins to override comment ratings
  packages/api/prisma/migrations/20221019083532_override_rating/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/db/comment.ts
  packages/api/src/graphql/blocks.ts
  packages/api/src/graphql/comment-rating/comment-rating.public-mutation.ts
  packages/api/src/graphql/comment/comment.private-mutation.ts
  packages/api/src/graphql/comment/comment.private-queries.ts
  packages/api/src/graphql/comment/comment.public-queries.ts
  packages/api/src/graphql/comment/comment.ts
  packages/api/src/graphql/mutation.private.ts
  packages/editor/src/client/api/comment.graphql
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/strip-typename.ts
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/routes/comments/commentEditView.tsx
Labels: PR: New Feature :heart:

#749 fix: regenerated api test definitions
  packages/api/__tests__/api/private/index.ts
  packages/api/__tests__/api/public/index.ts
Labels: PR: Internal :house:

#759 fix(editor): sending typename to api
  packages/editor/src/client/blocks/types.ts
Labels: PR: Bug Fix :bug:

#763 fix(editor): image url wrong
  packages/editor/src/client/panel/imageEditPanel.tsx
Labels: PR: Bug Fix :bug:

#761 fix(api): peer articles sorting is the opposite way
  packages/api/src/graphql/peer-article/peer-article.private-queries.ts
Labels: PR: Bug Fix :bug:

#760 fix(api): focalpoint missing in queries and mutations
  packages/api/src/context.ts
  packages/api/src/graphql/image/image.private-mutation.ts
  packages/api/src/graphql/image/image.public-mutation.ts
  packages/api/src/graphql/image/image.public-queries.ts
  packages/api/src/graphql/image/image.queries.ts
Labels: PR: Bug Fix :bug:

#762 fix(editor): gif or other unsupported images by exfir upload broken
  packages/editor/src/client/atoms/imageMetaData.tsx
Labels: PR: Bug Fix :bug:

#767 Backport patch: Fix subscription csv download
  packages/api/src/graphql/query.private.ts
  packages/api/src/utility.ts
Labels: PR: Bug Fix :bug:
