Repository wepublish/wepublish, pull requests merged in 2022-05, with the labels that each got.

#580 refactor(editor): eliminate side effect when importing i18n
  packages/editor/__tests__/specs/i18n.test.tsx
  packages/editor/src/client/i18n.ts
  packages/editor/src/client/index.tsx
Labels: PR: Polish :nail_care:

#579 fix(editor): unnecessary recalcs in useUnsavedChangesDialog
  packages/editor/__tests__/specs/unsavedChangesDialog.test.tsx
  packages/editor/src/client/unsavedChangesDialog.tsx
Labels: PR: Bug Fix :bug:

#582 feat(editor): umlaute should also add an additional e in slugify
  packages/editor/__tests__/specs/__snapshots__/utility.test.ts.snap
  packages/editor/__tests__/specs/utility.test.ts
  packages/editor/src/client/utility.ts
Labels: PR: Bug Fix :bug:

#557 WPC-671: Caching and background autorefresh of remote content
  config/create-gke-manifest.js
  packages/api/package.json
  packages/api/src/context.ts
  yarn.lock
Labels: PR: Polish :nail_care:

#581 refactor(api-db-mongodb/api/editor): remove ts-ignores
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/events.ts
  packages/api/src/server.ts
  packages/editor/__tests__/specs/__snapshots__/authorEditPanel.tsx.snap
  packages/editor/__tests__/specs/__snapshots__/userEditPanel.tsx.snap
  packages/editor/__tests__/specs/authorEditPanel.tsx
  packages/editor/__tests__/specs/peerEditPanel.tsx
  packages/editor/__tests__/specs/userEditPanel.tsx
  packages/editor/package.json
  packages/editor/src/client/base.tsx
  packages/editor/src/client/blocks/richTextBlock/richTextBlock.tsx
  packages/editor/src/client/index.tsx
  packages/editor/src/client/panel/authorEditPanel.tsx
  packages/editor/src/client/panel/userEditPanel.tsx
  packages/editor/src/client/routes/peerList.tsx
  yarn.lock
Labels: PR: Polish :nail_care:

#587 b/WPC-691: Own pending comment wrong data structure
  packages/api-db-mongodb/src/db/comment.ts
  packages/api/src/db/comment.ts
  packages/api/src/graphql/comment.ts
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:

#583 WPC-103 Subscription filters
  examples/api/.env.example
  packages/api-db-mongodb/src/db/subscription.ts
  packages/api/src/db/subscription.ts
  packages/api/src/graphql/query.private.ts
  packages/api/src/graphql/subscription.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/api/subscription.graphql
  packages/editor/src/client/locales/de.json
  packages/editor/src/client/locales/en.json
  packages/editor/src/client/locales/fr.json
  packages/editor/src/client/panel/ExportSubscriptionsCsvModal.tsx
  packages/editor/src/client/panel/subscriptionEditPanel.tsx
  packages/editor/src/client/routes/subscriptionList.tsx
Labels: PR: New Feature :heart:

#550 fix layout for iframe embed
  examples/website/src/shared/utility.ts
  packages/api-db-mongodb/src/migration.ts
  packages/api/src/db/block.ts
  packages/api/src/graphql/blocks.ts
  packages/editor/src/client/api/index.ts
  packages/editor/src/client/blocks/embeds/iframe.tsx
  packages/editor/src/client/blocks/types.ts
  packages/editor/src/client/panel/embedEditPanel.tsx
  packages/editor/src/client/utility.ts
Labels: PR: Bug Fix :bug:

#595 bugfix for missing variable in the sendMail command
  packages/api/src/memberContext.ts
Labels: PR: Bug Fix :bug:

#597 fix sorting for subscriptions query
  packages/api/src/db/subscription.ts
  packages/api/src/graphql/subscription.ts
Labels: PR: Bug Fix :bug:

#588 FormatISO dates while generating csv
  packages/api/package.json
  packages/api/src/utility.ts
  yarn.lock
Labels: PR: Bug Fix :bug:

#599 bugfix: added missing canceledAt field in graphQL publicInvoice
  packages/api/src/graphql/invoice.ts
Labels: PR: Bug Fix :bug:

#596 fix for the mongodb adpater to use the skip function for getInvoices
  packages/api-db-mongodb/src/db/invoice.ts
Labels: PR: Bug Fix :bug:

#586 b/WPC-690-Missing-CommentState-Type-in-GraphQL-Schema
  packages/api/src/graphql/comment.ts
Labels: PR: Bug Fix :bug:
