Repository wepublish/wepublish, pull requests merged in 2023-02, with the labels that each got.

#841 docs(*): Add deployment docs
  docs/deployments.md
Labels: PR: Docs :memo:

#842 chore: Do not publish demo docker images
  .github/workflows/publish-master-artifacts.yml
Labels: PR: Internal :house:

#828 B/wep 942 peering timeouts on production
  apps/editor/src/app/locales/de.json
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/locales/fr.json
  apps/editor/src/app/panel/teaserSelectPanel.tsx
  libs/api/package.json
  libs/api/src/lib/context.ts
  libs/api/src/lib/graphql/peer-article/peer-article.private-queries.ts
  libs/api/src/lib/graphql/query.private.ts
  libs/editor/api/src/lib/graphql.ts
  libs/editor/api/src/lib/schemas/article.graphql
Labels: PR: Bug Fix :bug:

#868 bugfix for tables disappearing in richtext block
  apps/editor/src/app/blocks/richTextBlock/editor/render.tsx
  apps/editor/src/app/blocks/richTextBlock/toolbar/tableMenu.tsx
Labels: PR: Bug Fix :bug:
