Repository wepublish/wepublish, pull requests merged in 2023-01, with the labels that each got.

#781 chore: removing things leftover from package removals
  config/create-gke-manifest.js
  config/notify-github.js
  config/notify-jira.js
  docker-compose.yml
  examples/api/nodemon.json
  examples/api/package.json
  package.json
  yarn.lock
Labels: PR: Internal :house:

#802 chore: replace yarn with npm
  .dockerignore
  .env.local
  .github/workflows/deploy-to-k8s.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .github/workflows/pr_close.yml
  .github/workflows/publish-npm-packages.yml
  .github/workflows/test.yml
  .gitignore
  .npmrc
  Dockerfile
  FAQ.md
  README.md
  apps/website-example/webpack.config.js
  config/create-gke-manifest.js
  config/package-lock.json
  config/package.json
  config/yarn.lock
  docs/README.md
  docs/Releases.md
  docs/commenting.md
  docs/prisma.md
  helm/charts/wepublish/templates/deployment-api.yaml
  lerna.json
  libs/api/__tests__/specs/__snapshots__/peer.test.ts.snap
  libs/api/__tests__/specs/peer.test.ts
  libs/api/package.json
  package-lock.json
  package.json
  yarn.lock
Labels: PR: Internal :house:

#809 fix(api): make author name filter case insensitive
  libs/api/__tests__/specs/author.test.ts
  libs/api/src/lib/graphql/author/author.queries.ts
  package-lock.json
Labels: PR: Bug Fix :bug:

#821 fix(editor): membership create
  apps/editor/src/app/panel/memberPlanEditPanel.tsx
Labels: PR: Bug Fix :bug:

#804 B/WPC-981-CancelationBugFixPayrexxSubscription
  libs/api/src/lib/payments/payrexxSubscriptionPaymentProvider.ts
Labels: PR: Bug Fix :bug:

#801 feat(api): new phrase API to do full text search on articles and pages
  libs/api/__tests__/api/public/index.ts
  libs/api/__tests__/api/public/phrase.graphql
  libs/api/__tests__/specs/phrase.test.ts
  libs/api/__tests__/utility.ts
  libs/api/prisma/migrations/20221229154843_rename_page_revision_table/migration.sql
  libs/api/prisma/migrations/20221229154844_unwrap_array_of_jsonb/migration.sql
  libs/api/prisma/migrations/20221229154845_page_article_fulltext_index/migration.sql
  libs/api/prisma/schema.prisma
  libs/api/src/lib/context.ts
  libs/api/src/lib/db/article.ts
  libs/api/src/lib/db/page.ts
  libs/api/src/lib/graphql/phrase/phrase.public-queries.ts
  libs/api/src/lib/graphql/phrase/phrase.ts
  libs/api/src/lib/graphql/query.public.ts
Labels: PR: New Feature :heart:

#827 chore: add no unused imports eslint rule
  .eslintrc.json
  apps/editor/src/app/panel/articleMetadataPanel.tsx
  apps/editor/src/app/routes/comments/commentEditView.tsx
  apps/editor/src/app/routes/comments/commentList.tsx
  package-lock.json
  package.json
Labels: PR: Internal :house:

#838 Rework update helm chart (prepare for nx, consolidate and simplify)
  .github/workflows/release-helm-chart.yml
  helm/charts/website/Chart.yaml
  helm/charts/website/templates/_helpers.tpl
  helm/charts/website/templates/deployment.yaml
  helm/charts/website/templates/ingress.yaml
  helm/charts/website/templates/secrets.yaml
  helm/charts/website/templates/service.yml
  helm/charts/website/values.yaml
  helm/charts/wepublish/Chart.yaml
  helm/charts/wepublish/templates/api.yaml
  helm/charts/wepublish/templates/deployment-api.yaml
  helm/charts/wepublish/templates/deployment-editor.yaml
  helm/charts/wepublish/templates/editor.yaml
  helm/charts/wepublish/templates/ingress.yaml
  helm/charts/wepublish/templates/secrets.yaml
  helm/charts/wepublish/templates/service.yml
  helm/charts/wepublish/templates/website.yaml
  helm/charts/wepublish/values.yaml
Labels: PR: Internal :house:

#833 Fix pages and articles views
  apps/editor/src/app/routes/articleList.tsx
  apps/editor/src/app/routes/pageList.tsx
Labels: PR: Bug Fix :bug:
