Repository wepublish/wepublish, pull requests merged in 2023-05, with the labels that each got.

#897 Change comment character limit
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/routes/settingList.tsx
  libs/api/__tests__/api/private/index.ts
  libs/api/prisma/seed.ts
  libs/api/src/lib/error.ts
  libs/api/src/lib/graphql/comment/comment.public-mutation.ts
  libs/api/src/lib/graphql/setting.ts
  libs/api/src/lib/utility.ts
  libs/editor/api/src/lib/graphql.ts
  libs/settings/api/src/lib/setting.ts
Labels: PR: New Feature :heart:

#898 Add bg color to datepicker
  apps/editor/src/app/atoms/dateTimePicker.tsx
Labels: PR: Bug Fix :bug:, PR: Polish :nail_care:

#903 build(js): fix the same library being moved by nx using a patch
  .eslintrc.json
  libs/api/project.json
  libs/api/tsconfig.lib.json
  libs/authentication/api/project.json
  libs/authentication/api/tsconfig.lib.json
  libs/consent/api/project.json
  libs/consent/api/tsconfig.lib.json
  libs/membership/api/project.json
  libs/membership/api/tsconfig.lib.json
  libs/nest-modules/project.json
  libs/permissions/api/project.json
  libs/permissions/api/tsconfig.lib.json
  libs/settings/api/project.json
  libs/settings/api/tsconfig.lib.json
  libs/user/api/project.json
  libs/user/api/tsconfig.lib.json
  package-lock.json
  package.json
  patches/@nrwl+js+15.3.0.patch
Labels: PR: Bug Fix :bug:, PR: Internal :house:

#887 WPC-1099: Improved user first/lastname search
  libs/api/src/lib/graphql/user/user.queries.ts
Labels: PR: Bug Fix :bug:

#900 b/WPC-1155 Urgent bug in invoice mark as manually paid
  apps/editor/src/app/atoms/invoice.tsx
  libs/api/__tests__/api/private/index.ts
  libs/api/__tests__/api/public/index.ts
  libs/api/prisma/migrations/20230515133433_fix_wrong_manualy_mark_as_paid/migration.sql
  libs/api/src/lib/graphql/invoice/invoice.private-mutation.ts
  libs/api/src/lib/graphql/mutation.private.ts
  libs/api/src/lib/payments/payrexxSubscriptionPaymentProvider.ts
  libs/editor/api/src/lib/graphql.ts
  libs/editor/api/src/lib/schemas/invoice.graphql
  libs/website/api/src/lib/graphql.ts
Labels: PR: Bug Fix :bug:

#927 feat(api): add event to url adapter
  apps/api-example/src/app/url-adapter.ts
  libs/api/__tests__/utility.ts
  libs/api/src/lib/graphql/event/event.ts
  libs/api/src/lib/urlAdapter.ts
Labels: PR: Breaking Change :boom:, PR: New Feature :heart:

#931 WPC-1198-fixing-error-in-migration-to-convert-jsonb_array-to-jsonb
  libs/api/prisma/migrations/20221229154844_unwrap_array_of_jsonb/migration.sql
Labels: PR: Bug Fix :bug:

#932 WPC-1124: Event Teaser
  apps/editor/src/app/blocks/teaserGridBlock.tsx
  apps/editor/src/app/blocks/teaserGridFlexBlock.tsx
  apps/editor/src/app/blocks/types.ts
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/panel/teaserEditPanel.tsx
  apps/editor/src/app/panel/teaserSelectPanel.tsx
  libs/api/__tests__/api/private/block.graphql
  libs/api/__tests__/api/private/index.ts
  libs/api/src/lib/context.ts
  libs/api/src/lib/db/block.ts
  libs/api/src/lib/graphql/blocks.ts
  libs/api/src/lib/utility.ts
  libs/editor/api/src/lib/graphql.ts
  libs/editor/api/src/lib/schemas/block.graphql
Labels: PR: New Feature :heart:

#935 timepicker alignment
  apps/editor/src/app/atoms/dateTimePicker.tsx
Labels: PR: Polish :nail_care:

#938 feat(website): footer implementation
  libs/navigation/website/src/index.ts
  libs/navigation/website/src/lib/footer/__snapshots__/footer-container.spec.tsx.snap
  libs/navigation/website/src/lib/footer/__snapshots__/footer.spec.tsx.snap
  libs/navigation/website/src/lib/footer/footer-container.spec.tsx
  libs/navigation/website/src/lib/footer/footer-container.stories.tsx
  libs/navigation/website/src/lib/footer/footer-container.tsx
  libs/navigation/website/src/lib/footer/footer.spec.tsx
  libs/navigation/website/src/lib/footer/footer.stories.tsx
  libs/navigation/website/src/lib/footer/footer.tsx
  libs/navigation/website/src/lib/navbar/navbar-container.stories.tsx
  libs/website/src/lib/website.provider.tsx
Labels: PR: New Feature :heart:

#945 feat(website): session context implementation
  libs/authentication/website/.babelrc
  libs/authentication/website/.eslintrc.json
  libs/authentication/website/README.md
  libs/authentication/website/jest.config.ts
  libs/authentication/website/project.json
  libs/authentication/website/src/index.ts
  libs/authentication/website/src/lib/session.context.ts
  libs/authentication/website/tsconfig.json
  libs/authentication/website/tsconfig.lib.json
  libs/authentication/website/tsconfig.spec.json
Labels: PR: New Feature :heart:

#940 Public pages query fix
  libs/api/src/lib/graphql/query.public.ts
Labels: PR: Bug Fix :bug:

#948 add public properties on public user
  libs/api/src/lib/graphql/user.ts
Labels: PR: Bug Fix :bug:

#941 Fix metadata panel add new author
  libs/api/prisma/migrations/20230524093017_optional_bio_author/migration.sql
  libs/api/prisma/schema.prisma
Labels: PR: Bug Fix :bug:
