Repository wepublish/wepublish, pull requests merged in 2023-04, with the labels that each got.

#885 feat(api-example): allow mailchimp and add env var for sender
  .env
  apps/api-example/src/app/index.ts
Labels: PR: New Feature :heart:, PR: Bug Fix :bug:

#890 Security fix expose docker-compose ports only localy
  docker-compose.yml
Labels: PR: Bug Fix :bug:

#895 Allow user to edit own comment
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/routes/settingList.tsx
  libs/api/prisma/seed.ts
  libs/api/src/lib/db/comment.ts
  libs/api/src/lib/graphql/comment/comment.public-mutation.ts
  libs/api/src/lib/graphql/comment/comment.public-queries.ts
  libs/api/src/lib/graphql/comment/comment.ts
  libs/api/src/lib/graphql/mutation.public.ts
  libs/api/src/lib/graphql/setting.ts
  libs/editor/api/src/lib/graphql.ts
  libs/settings/api/src/lib/setting.ts
Labels: PR: New Feature :heart:

#888 WPC-1087- Added credentials to readme
  README.md
Labels: PR: Docs :memo:
