Repository wepublish/wepublish, pull requests merged in 2023-03, with the labels that each got.

#870 fix: master broken from 9.0.0 merge
  apps/editor/src/app/panel/selectEventsPanel.tsx
  libs/api/__tests__/api/private/index.ts
  libs/api/__tests__/api/public/index.ts
  libs/api/src/lib/context.ts
  libs/api/src/lib/graphql/query.private.ts
  libs/editor/api/src/lib/graphql.ts
Labels: PR: Internal :house:

#819 dashboard
  apps/editor/.eslintrc.json
  apps/editor/src/app/app.tsx
  apps/editor/src/app/atoms/dashboard/activityFeed.tsx
  apps/editor/src/app/atoms/dashboard/subscriberChart.tsx
  apps/editor/src/app/base.tsx
  apps/editor/src/app/locales/de.json
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/locales/fr.json
  apps/editor/src/app/routes/dashboard.tsx
  libs/api/__tests__/api/private/index.ts
  libs/api/src/lib/context.ts
  libs/api/src/lib/db/action.ts
  libs/api/src/lib/db/subscription.ts
  libs/api/src/lib/graphql/action.ts
  libs/api/src/lib/graphql/action/action.private-queries.ts
  libs/api/src/lib/graphql/query.private.ts
  libs/api/src/lib/graphql/subscription.ts
  libs/api/src/lib/graphql/subscription/subscription.private-queries.ts
  libs/editor/api/src/lib/graphql.ts
  libs/editor/api/src/lib/schemas/action.graphql
  libs/editor/api/src/lib/schemas/subscription.graphql
Labels: PR: New Feature :heart:

#873 fix(api): add onDelete cascade for authors and revisions
  libs/api/prisma/migrations/20230315152758_article_revision_author_on_delete_cascade/migration.sql
  libs/api/prisma/schema.prisma
Labels: PR: Bug Fix :bug:

#875 fix(editor): user filter being wrong after graphql changes
  apps/editor/src/app/atoms/searchAndFilter/userSearch.tsx
  apps/editor/src/app/panel/userCheckPicker.tsx
Labels: PR: Bug Fix :bug:

#878 build(editor/website-example): typescript 4.7 introduced a bug which caused the build to silently fail
  apps/editor/src/app/atoms/comment/commentStateDropdown.tsx
  apps/editor/src/app/atoms/listInput.tsx
  apps/editor/src/app/atoms/poll/pollAnswers.tsx
  apps/editor/src/app/atoms/poll/pollExternalVotes.tsx
  apps/editor/src/app/blocks/teaserGridBlock.tsx
  apps/editor/src/app/blocks/teaserGridFlexBlock.tsx
  apps/editor/src/app/panel/embedEditPanel.tsx
  apps/editor/src/app/panel/navigationEditPanel.tsx
  apps/editor/src/app/panel/selectCommentsPanel.tsx
  apps/editor/src/app/panel/selectPollPanel.tsx
  apps/editor/src/app/panel/teaserSelectPanel.tsx
  apps/editor/src/app/routes/commentRatingEditView.tsx
  package-lock.json
  package.json
Labels: PR: Bug Fix :bug:

#879 Display dashboard actions in correct order
  libs/api/src/lib/graphql/action/action.private-queries.ts
Labels: PR: Bug Fix :bug:

#881 Remove extra scrollbars
  apps/editor/src/app/base.tsx
Labels: PR: Bug Fix :bug:

#880 Settings page improvements
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/routes/settingList.tsx
  package-lock.json
Labels: PR: Polish :nail_care:
