Repository wepublish/wepublish, pull requests merged in 2024-04, with the labels that each got.

#1268 Bumped github workflow version
  .github/workflows/lint.yml
  .github/workflows/on-pr-review.yml
  .github/workflows/on-tag-publish-npm-packages.yml
  .github/workflows/test.yml
  .github/workflows/website-tests.yml
Labels: PR: Internal :house:

#1236 fix(config): Fix error message for Unknown mail provider type defined
  apps/api-example/src/nestapp/app.module.ts
Labels: PR: Bug Fix :bug:

#1308 HOTFIX: Prevent creation of multiple invoices
  libs/membership/api/src/lib/subscription/subscription.service.spec.ts
  libs/membership/api/src/lib/subscription/subscription.service.ts
Labels: PR: Bug Fix :bug:

#1307 GRUP-12: Allow linking image blocks to a URL
  apps/editor/src/app/locales/de.json
  apps/editor/src/app/locales/en.json
  apps/editor/src/app/locales/fr.json
  libs/api/__tests__/api/private/index.ts
  libs/api/__tests__/api/public/index.ts
  libs/api/src/lib/db/block.ts
  libs/api/src/lib/graphql/blocks.ts
  libs/block-content/website/src/lib/image/__snapshots__/image-block.spec.tsx.snap
  libs/block-content/website/src/lib/image/image-block.stories.tsx
  libs/block-content/website/src/lib/image/image-block.tsx
  libs/editor/api/src/lib/graphql.ts
  libs/editor/api/src/lib/schemas/block.graphql
  libs/ui/editor/src/lib/blocks/imageBlock.tsx
  libs/ui/editor/src/lib/blocks/types.ts
  libs/ui/editor/src/lib/panel/imageEditPanel.tsx
  libs/website/api/src/lib/graphql.ts
  libs/website/api/src/lib/schemas/block-content.graphql
Labels: PR: New Feature :heart:
