Repository wepublish/wepublish, pull requests merged in 2024-03, with the labels that each got.

#1207 WPC-1499 create invoice by subscription period not by invoice
  libs/membership/api/src/lib/periodic-job/periodic-job.service.spec.ts
  libs/membership/api/src/lib/subscription/subscription.service.spec.ts
  libs/membership/api/src/lib/subscription/subscription.service.ts
Labels: PR: Bug Fix :bug:

#1237 feat(babanews): Add babanews website based on website-example
  apps/babanews/.eslintrc.json
  apps/babanews/index.d.ts
  apps/babanews/jest.config.ts
  apps/babanews/next-env.d.ts
  apps/babanews/next.config.js
  apps/babanews/pages/[slug].tsx
  apps/babanews/pages/_app.tsx
  apps/babanews/pages/a/[slug].tsx
  apps/babanews/pages/a/index.tsx
  apps/babanews/pages/a/tag/[tag].tsx
  apps/babanews/pages/api/atom-feed.ts
  apps/babanews/pages/api/json-feed.ts
  apps/babanews/pages/api/rss-feed.ts
  apps/babanews/pages/api/sitemap.ts
  apps/babanews/pages/author/[slug].tsx
  apps/babanews/pages/author/index.tsx
  apps/babanews/pages/event/[id].tsx
  apps/babanews/pages/event/index.tsx
  apps/babanews/pages/index.tsx
  apps/babanews/pages/login.tsx
  apps/babanews/pages/mitmachen.tsx
  apps/babanews/pages/p/[peerId]/[articleId].tsx
  apps/babanews/pages/profile/index.tsx
  apps/babanews/pages/profile/subscription/[id].tsx
  apps/babanews/pages/profile/subscription/deactivated.tsx
  apps/babanews/pages/profile/subscription/index.tsx
  apps/babanews/pages/signup.tsx
  apps/babanews/project.json
  apps/babanews/public/android-chrome-192x192.png
  apps/babanews/public/apple-touch-icon.png
  apps/babanews/public/browserconfig.xml
  apps/babanews/public/favicon-16x16.png
  apps/babanews/public/favicon-32x32.png
  apps/babanews/public/favicon.ico
  apps/babanews/public/mstile-150x150.png
  apps/babanews/public/robots.txt
  apps/babanews/public/safari-pinned-tab.svg
  apps/babanews/public/site.webmanifest
  apps/babanews/src/feed.ts
  apps/babanews/src/logo.svg
  apps/babanews/src/sitemap.ts
  apps/babanews/src/styles/tsri-article.styles.tsx
  apps/babanews/src/tsri-break-block.tsx
  apps/babanews/src/tsri-button.tsx
  apps/babanews/src/tsri-paragraph.tsx
  apps/babanews/tsconfig.json
  apps/babanews/tsconfig.spec.json
Labels: PR: New Feature :heart:

#1238 feat(ci/cd): Push ghcr.io/wepublish/*:master images
  .github/workflows/on-master-publish-master-artifacts.yml
Labels: PR: Internal :house:
