Repository wepublish/wepublish, pull requests merged in 2024-02, with the labels that each got.

#1162 Fixe mailgun overflow bug
  libs/mail/api/src/lib/mail-provider/mailgun-mail-provider.ts
  libs/membership/api/src/lib/periodic-job/periodic-job.service.ts
Labels: PR: Bug Fix :bug:

#1166 Include CONFIG_FILE_PATH in helm chart
  helm/charts/wepublish/Chart.yaml
  helm/charts/wepublish/values.yaml
Labels: PR: Internal :house:

#1170 WPC-1473 Add healthcheck
  .env
  apps/api-example/src/nestapp/app.module.ts
  libs/api/src/index.ts
  libs/health/api/.babelrc
  libs/health/api/.eslintrc.json
  libs/health/api/jest.config.ts
  libs/health/api/package.json
  libs/health/api/project.json
  libs/health/api/setup-database.js
  libs/health/api/src/index.ts
  libs/health/api/src/lib/health.controller.ts
  libs/health/api/src/lib/health.module.ts
  libs/health/api/tsconfig.json
  libs/health/api/tsconfig.lib.json
  libs/health/api/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: PR: New Feature :heart:

#1174 Use s3 compatible media server with health check support
  .github/workflows/review-deployment.yml
  docker-compose.yml
Labels: PR: Internal :house:

#1177 Bump node version to 18
  .nvmrc
  Dockerfile
  config/package-lock.json
  config/package.json
  package-lock.json
  package.json
Labels: PR: Internal :house:

#1179 fix docker run on m1 chip
  docker-compose.yml
Labels: PR: Internal :house:

#1188 Bump version to 18 and fixe leap year test bug
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/website-tests.yml
  libs/membership/api/src/lib/subscription/subscription.service.spec.ts
Labels: PR: Internal :house:
